### ISSUE TITLE
error: 'AliceO2' has not been declared  using namespace AliceO2::Configuration

### ISSUE THREAD

**Issue by frmanso** [AliceO2Group/AliceO2#1016]
Hello,
    I'm getting an error from the O2 building of my dev branch (up to date) since yesterday. See the attached log file.

==> Building O2@dev
==> O2 is being built (use --debug for full output): failed    
ERROR: Error while executing /home/manso/aliceO2/sw/SPECS/ubuntu1404_x86-64/O2/dev-1/build.sh on `clraliceport15'.

Thanks for the help.
F.M.

[log.txt](https://github.com/AliceO2Group/AliceO2/files/1946200/log.txt)

**Comment by knopers8** [comment]
Hello,
are you absolutely sure, that you have up to date dev branch? The PR that updates this namespace was merged yesterday ( https://github.com/AliceO2Group/AliceO2/pull/992/files ).

**Comment by frmanso** [comment]
Hello,
    I have performed a git pull --rebase in O2 directory yesterday but also this morning and all was up to date...
But looking into my DataSampling.cxx file, I have these 3 lines instead of 4:

using namespace o2::framework;
using namespace o2::framework::DataSamplingConfig;
using namespace AliceO2::Configuration;

In fact, there is no line "using namespace o2::configuration;" in my DataSampling file.
What should I do? Add the missing line by hand?

F.M.

**Comment by frmanso** [comment]
Hello,
    The alidist update was already performed yesterday and this morning but without success.
Now, imposing to fetch the dev source, I can build O2.
Thanks, best regards.
