### ISSUE TITLE
Crash in geometry drawing 

### ISSUE THREAD

**Issue by frmanso** [AliceO2Group/AliceO2#1048]
Hello,
    the drawing of the geometry file (O2 and alidist up to date today, ubuntu14.04 LTS) is crashing using the standard drawing commands:

TGeoManager::Import("geofile_mft.root");
TGeoVolume *t = gGeoManager->GetVolume("MFT");
gGeoManager->SetVisLevel(10);
t->Draw("ogl");

The error message is:

root [0] .x drawGeometry.C 
Info in <TGeoManager::Import>: Reading geometry from file: geofile_mft.root
Info in <TGeoManager::CloseGeometry>: Geometry loaded from file...
Info in <TGeoManager::SetTopVolume>: Top volume is cave. Master volume is cave
Info in <TGeoNavigator::BuildCache>: --- Maximum geometry depth set to 100
Info in <TGeoManager::Voxelize>: Voxelizing...
Info in <TGeoManager::CountLevels>: max level = 7, max placements = 105
Info in <TGeoManager::CloseGeometry>: 48180 nodes/ 23157 volume UID's in FAIR geometry
Info in <TGeoManager::CloseGeometry>: ----------------modeler ready----------------
Info in <TGeoManager::SetVisLevel>: Automatic visible depth disabled
Info in <TCanvas::MakeDefCanvas>:  created default TCanvas with name c1

 *** Break *** segmentation violation

===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007fae4863da0c in waitpid () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fae485c3232 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007fae49715f92 in TUnixSystem::Exec (shellcmd=<optimized out>, this=0xba7570) at /home/manso/aliceO2/sw/SOURCES/ROOT/v6-12-04/v6-12-04/core/unix/src/TUnixSystem.cxx:2118
#3  TUnixSystem::StackTrace (this=0xba7570) at /home/manso/aliceO2/sw/SOURCES/ROOT/v6-12-04/v6-12-04/core/unix/src/TUnixSystem.cxx:2412
#4  0x00007fae4971848c in TUnixSystem::DispatchSignals (this=0xba7570, sig=kSigSegmentationViolation) at /home/manso/aliceO2/sw/SOURCES/ROOT/v6-12-04/v6-12-04/core/unix/src/TUnixSystem.cxx:3643
#5  <signal handler called>
#6  0x00007fae4893b998 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#7  0x00007fae36119724 in TGCompositeFrame::MapSubwindows (this=<optimized out>) at /home/manso/aliceO2/sw/SOURCES/ROOT/v6-12-04/v6-12-04/gui/gui/src/TGFrame.cxx:1162
#8  0x00007fae22186a10 in TGLSAViewer::CreateFrames (this=0x1559d970) at /home/manso/aliceO2/sw/SOURCES/ROOT/v6-12-04/v6-12-04/graf3d/gl/src/TGLSAViewer.cxx:461
#9  0x00007fae22186dcd in TGLSAViewer::TGLSAViewer (this=0x1559d970, pad=<optimized out>, format=<optimized out>) at /home/manso/aliceO2/sw/SOURCES/ROOT/v6-12-04/v6-12-04/graf3d/gl/src/TGLSAViewer.cxx:231
#10 0x00007fae2d54d06b in ?? ()
#11 0x00000000154eb0e0 in ?? ()
#12 0x00007fae446574dd in std::_Function_handler<llvm::Expected<unsigned long> (), llvm::orc::RTDyldObjectLinkingLayer::ConcreteLinkedObject<std::shared_ptr<llvm::RuntimeDyld::MemoryManager>, std::shared_ptr<llvm::JITSymbolResolver>, llvm::orc::RTDyldObjectLinkingLayer::addObject(std::shared_ptr<llvm::object::OwningBinary<llvm::object::ObjectFile> >, std::shared_ptr<llvm::JITSymbolResolver>)::{lambda(std::_List_iterator<std::unique_ptr<llvm::orc::RTDyldObjectLinkingLayerBase::LinkedObject, std::default_delete<llvm::orc::RTDyldObjectLinkingLayerBase::LinkedObject> > >, llvm::RuntimeDyld&, std::shared_ptr<llvm::object::OwningBinary<llvm::object::ObjectFile> > const&, std::function<void ()>)#1}>::getSymbolMaterializer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda()#1}>::_M_invoke(std::_Any_data const&) () from /home/manso/aliceO2/sw/ubuntu1404_x86-64/ROOT/v6-12-04-2/lib/libCling.so
#13 0x00007fae44661d02 in llvm::orc::LazyEmittingLayer<llvm::orc::IRCompileLayer<cling::IncrementalJIT::RemovableObjectLinkingLayer, llvm::orc::SimpleCompiler> >::EmissionDeferredModule::find(llvm::StringRef, bool, llvm::orc::IRCompileLayer<cling::IncrementalJIT::RemovableObjectLinkingLayer, llvm::orc::SimpleCompiler>&)::{lambda()#1}::operator()() const () from /home/manso/aliceO2/sw/ubuntu1404_x86-64/ROOT/v6-12-04-2/lib/libCling.so
#14 0x0000000000c22ce0 in ?? ()
#15 0x00000000152f4a78 in ?? ()
#16 0x00007fae44658a76 in cling::IncrementalExecutor::getPointerToGlobalFromJIT(llvm::GlobalValue const&) () from /home/manso/aliceO2/sw/ubuntu1404_x86-64/ROOT/v6-12-04-2/lib/libCling.so
#17 0x0000000000000000 in ?? ()
===========================================================

The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum.
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00007fae4893b998 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#7  0x00007fae36119724 in TGCompositeFrame::MapSubwindows (this=<optimized out>) at /home/manso/aliceO2/sw/SOURCES/ROOT/v6-12-04/v6-12-04/gui/gui/src/TGFrame.cxx:1162
#8  0x00007fae22186a10 in TGLSAViewer::CreateFrames (this=0x1559d970) at /home/manso/aliceO2/sw/SOURCES/ROOT/v6-12-04/v6-12-04/graf3d/gl/src/TGLSAViewer.cxx:461
#9  0x00007fae22186dcd in TGLSAViewer::TGLSAViewer (this=0x1559d970, pad=<optimized out>, format=<optimized out>) at /home/manso/aliceO2/sw/SOURCES/ROOT/v6-12-04/v6-12-04/graf3d/gl/src/TGLSAViewer.cxx:231
#10 0x00007fae2d54d06b in ?? ()
#11 0x00000000154eb0e0 in ?? ()
#12 0x00007fae446574dd in std::_Function_handler<llvm::Expected<unsigned long> (), llvm::orc::RTDyldObjectLinkingLayer::ConcreteLinkedObject<std::shared_ptr<llvm::RuntimeDyld::MemoryManager>, std::shared_ptr<llvm::JITSymbolResolver>, llvm::orc::RTDyldObjectLinkingLayer::addObject(std::shared_ptr<llvm::object::OwningBinary<llvm::object::ObjectFile> >, std::shared_ptr<llvm::JITSymbolResolver>)::{lambda(std::_List_iterator<std::unique_ptr<llvm::orc::RTDyldObjectLinkingLayerBase::LinkedObject, std::default_delete<llvm::orc::RTDyldObjectLinkingLayerBase::LinkedObject> > >, llvm::RuntimeDyld&, std::shared_ptr<llvm::object::OwningBinary<llvm::object::ObjectFile> > const&, std::function<void ()>)#1}>::getSymbolMaterializer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda()#1}>::_M_invoke(std::_Any_data const&) () from /home/manso/aliceO2/sw/ubuntu1404_x86-64/ROOT/v6-12-04-2/lib/libCling.so
#13 0x00007fae44661d02 in llvm::orc::LazyEmittingLayer<llvm::orc::IRCompileLayer<cling::IncrementalJIT::RemovableObjectLinkingLayer, llvm::orc::SimpleCompiler> >::EmissionDeferredModule::find(llvm::StringRef, bool, llvm::orc::IRCompileLayer<cling::IncrementalJIT::RemovableObjectLinkingLayer, llvm::orc::SimpleCompiler>&)::{lambda()#1}::operator()() const () from /home/manso/aliceO2/sw/ubuntu1404_x86-64/ROOT/v6-12-04-2/lib/libCling.so
#14 0x0000000000c22ce0 in ?? ()
#15 0x00000000152f4a78 in ?? ()
#16 0x00007fae44658a76 in cling::IncrementalExecutor::getPointerToGlobalFromJIT(llvm::GlobalValue const&) () from /home/manso/aliceO2/sw/ubuntu1404_x86-64/ROOT/v6-12-04-2/lib/libCling.so
#17 0x0000000000000000 in ?? ()
===========================================================

Thanks for the help.
F.M.

**Comment by benedikt-voelkel** [comment]
I experienced something similar but was not able to look into details until now. Does this appear for both, TGeant3 and TGeant4? Because there might be some internal things going on with some pointers

**Comment by frmanso** [comment]
Hello,
   Since 3 of us are concerned by the same issue, it's not related to the local installation of the software.

**Comment by frmanso** [comment]
Hello,
   Finally, I have found the solution. The issue was related to a bug of the version of root v6-12-04. One must use the v6-12-06, from https://root.cern.ch/content/release-61206 and the bug is explained on https://root.cern.ch/doc/v612/release-notes.html#release-6.1206 (root crashes when trying to start opengl viewer).
**By default in the aliceO2 installation, the root v6-12-04 is used, it should be changed to the 06 release.**
Thanks by advance, F. Manso.
