### ISSUE TITLE
DPL test test_Framework_test_ParallelProducer fails with (Timeout)

### ISSUE THREAD

**Issue by sawenzel** [AliceO2Group/AliceO2#1066]
This test is very often broken in pull request checks. It should be fixed or deactivated.

**Comment by awegrzyn** [comment]
In addition I've experienced the following test to fail:
- 49 - test_Framework_test_SimpleStatefulProcessing01 (Timeout)
- 72 - test_Framework_test_DataAllocator (Timeout)
- 73 - test_Framework_test_RootTreeReader (Timeout)
- 75 - test_Framework_test_WorkflowOptions (Timeout)
- 131 - test_Framework_test_SimpleStatefulProcessing01 (Timeout)
- 132 - test_Framework_test_SimpleStatefulProcessing01 (Timeout)
- 143 - test_Framework_test_ParallelProducer (Timeout)
- 154 - test_Framework_test_DataAllocator (Timeout)
- 155 - test_Framework_test_DataAllocator (Timeout)
- 156 - test_Framework_test_RootTreeReader (Timeout)
- 157 - test_Framework_test_WorkflowOptions (Timeout)
Is there any ETA to fix this? @ktf @matthiasrichter ?

**Comment by sawenzel** [comment]
I think we could indeed just modify the o2.sh recipe and ask ctest to execute framework tests not in parallel mode. This should help.

**Comment by dberzano** [comment]
@sawenzel as discussed this morning in WP3 I am addressing it now.

**Comment by dberzano** [comment]
alisw/alidist#1132

**Comment by ktf** [comment]
I suspect there is a race condition in one of the fairmq helper threads. Can I get a ptrace of when it hangs?

--
Ciao,
Giulio
