### ISSUE TITLE
FairRootManager->RegisterAny(...) doesn't find dictionary for std::vector<T> if using std::shared_ptr

### ISSUE THREAD

**Issue by KlewinS** [AliceO2Group/AliceO2#1186]
as requested by @sawenzel this issue is moved from FairRoot (https://github.com/FairRootGroup/FairRoot/issues/789) to O2.

Somehow the dictionary of `std::vector<o2::TPC::ClusterHardwareContainer8kb>` is not found at runtime if using `std::shared_ptr<std::vector<T>>` instead of a plain pointer.

It makes it even more strange that if the corresponding LinkDef.h contains the correct pragma statement for std::vector<T>, then the dictionary is not even found for the plain pointer.

The current workaround which seems to work at the moment for me is to remove the std::vector<T> pragma statement from the LinkDef.h and register first a plain pointer of the vector via RegisterAny() and afterwards the pointer of interest of the shared_ptr via the already known workaround with the `static auto tmpPtr = container.get();` (https://github.com/KlewinS/AliceO2/blob/da1987c06651391c4246f7f0963fffd1ce320d52/Detectors/TPC/reconstruction/src/ClustererTask.cxx#L90)

**Comment by sawenzel** [comment]
@KlewinS : I believe the problem is fixed. Can you please verify by compiling against the latest FairRoot dev HEAD?

**Comment by sawenzel** [comment]
We should close this when confirmed by @KlewinS.

**Comment by KlewinS** [comment]
looks good, thank you very much for the quick fix!

**Comment by KlewinS** [comment]
@sawenzel could ROOT have a similar problem as FairRoot?

when I try to access the data of the created root-file via

```
TFile *clusterFile = TFile::Open(filename.data());                               
TTree *clusterTree = (TTree*)clusterFile->Get("o2sim");                          
                                                                                   
std::vector<o2::TPC::ClusterHardwareContainer8kb>* clusters = nullptr;           
clusterTree->SetBranchAddress(Form("TPCClusterHW%i",sectorid),&clusters);
```

I get the error message 
`Error in <TTree::SetBranchAddress>: The pointer type given (vector<o2::TPC::ClusterHardwareContainerFixedSize<8192> >) does not correspond to the class needed (vector<o2::TPC::ClusterHardwareContainerFixedSize<8192u> >) by the branch: TPCClusterHW0`

There is a missing "u"... even trying to force the u by explicitly setting the pointer to
`std::vector<o2::TPC::ClusterHardwareContainerFixedSize<8192u>>* clusters = nullptr; `
does not help, still the same error message. And also writing explicitly the u into the LinkDef.h and corresponding typedef of the Container leads to the same error.

**Comment by sawenzel** [comment]
It seems a slightly different problem than before. The data gets written correctly and I believe I can even browse it in the TBrowser (can you confirm). 

Will try to dig into this a bit.

**Comment by KlewinS** [comment]
Yes, I can open the file with a TBrowser and I can see something (without any errors or warnings in the console). Unfortunately, the ClusterHardwareContainer is a bit ugly to display values directly, therefore I can't confirm yet that the content is meaningful.

**Comment by sawenzel** [comment]
Seems to be a bug in a ROOT: The following slightly modified version works for me (while I confirm that yours doesn't):
```
  TFile *clusterFile = TFile::Open("AliceO2_TGeant3.tpc.clusters_20_event.root");
  TTree *clusterTree = (TTree*)clusterFile->Get("o2sim");
  auto br = clusterTree->GetBranch("TPCClusterHW0");
  std::vector<o2::TPC::ClusterHardwareContainer8kb>* clusters = nullptr;
  br->SetAddress(&clusters);
  br->GetEntry(0);
```

So it seems to make a difference if you talk to the tree or to the branch directly. Maybe you can file a ticket to ROOT.

**Comment by KlewinS** [comment]
done
https://sft.its.cern.ch/jira/browse/ROOT-9459

**Comment by ferdymercury** [comment]
Seems to be fixed in ROOT master, JIRA ticket was just closed. Could you confirm @KlewinS ? If not, please reopen issue on ROOT's GitHub.
