### ISSUE TITLE
Warnings volume deletion at end of simulation run

### ISSUE THREAD

**Issue by benedikt-voelkel** [AliceO2Group/AliceO2#1191]
After the simulation run there are now 4 new warnings in case of TGeant4
```
WARNING - Attempt to delete the physical volume store while geometry closed !
WARNING - Attempt to delete the logical volume store while geometry closed !
WARNING - Attempt to delete the solid store while geometry closed !
WARNING - Attempt to delete the region store while geometry closed !
```
Does this have any impact on the simulation?
This seems to be related to the method `G4RunManager::ReinitializeGeometry` cleaning these stores in exactly the same order the warnings appear in.

**Comment by sawenzel** [comment]
Can you post the warnings here?

**Comment by benedikt-voelkel** [comment]
Warnings do not appear anymore.
