### ISSUE TITLE
O2 does not compile with aliBuild

### ISSUE THREAD

**Issue by haavardh** [AliceO2Group/AliceO2#121]
I tried to compile O2 with aliBuild on SLC6 using 

```
scl enable devtoolset-2 bash

aliBuild init AliRoot,O2 -z ali-master
cd ali-master
aliBuild -z -w ../sw -d build O2
```

but there seems to be a problem related to libAliHLTTPC.so. AliRoot compiles correctly in the same setup. 

The last messages are quoted below:

> ERROR:O2:ali-master: Error while executing /nfs/usb/data/alice/sw/SPECS/slc6_x86-64/O2/master-1/build.sh on `pchaavard'.
> ERROR:O2:ali-master: Log can be found in /nfs/usb/data/alice/sw/BUILD/O2-latest-ali-master/log.
> ERROR:O2:ali-master: Please attach this file if you intend to request support.
> ERROR:O2:ali-master: Build directory is /nfs/usb/data/alice/sw/BUILD/O2-latest-ali-master/O2.
> ERROR:O2:ali-master: 
> ERROR:O2:ali-master: Note that you have packages in development mode.
> ERROR:O2:ali-master: Devel sources are not updated automatically, you must do it by hand.
> ERROR:O2:ali-master: This problem might be due to one or more outdated devel sources.
> ERROR:O2:ali-master: To update all development packages required for this build it is usually sufficient to do:
> ERROR:O2:ali-master: 
> ERROR:O2:ali-master:   ( cd AliRoot && git pull --rebase )
> ERROR:O2:ali-master:   ( cd O2 && git pull --rebase )
> 

I have tried to update software (using git pull), but this does not help.

The log file /nfs/usb/data/alice/sw/BUILD/O2-latest-ali-master/log is attached (rename log.txt to satisfy gitHub..)
[log.txt](https://github.com/AliceO2Group/AliceO2/files/330265/log.txt)

git status in the directory ali-master/alidist gives:

>  pchaavard:/nfs/usb/data/alice/ali-master/alidist$ git status 
>  # On branch IB/v5-08/prod
>  nothing to commit (working directory clean)
 
I am grateful if you can have a look at this!

Håvard Helstrup

**Comment by ktf** [comment]
I've done a few fixes to O2 and FairRoot in the last few days. Can you update to the tip of the `IB/v5-08/o2` branch and try again?

**Comment by ktf** [comment]
Closing after 17 days. Feel free to reopen if this is still an issue.
