### ISSUE TITLE
clusterizer-workflow

### ISSUE THREAD

**Issue by KlewinS** [AliceO2Group/AliceO2#1221]
I just learned that the digitizer-workflow is already in place and could be used. Would it be possible to also add a clusterizer-workflow on a short timescale, at least for the TPC?

**Comment by sawenzel** [comment]
Yes. In principle it is foreseen to connect the digitizer-workflow with the reco workflow started by @matthiasrichter. Probably this is not going to happen before CHEP18.

**Comment by sawenzel** [comment]
This ticket is now tracked as https://alice.its.cern.ch/jira/browse/O2-270?filter=-2.
Closing it here.
