### ISSUE TITLE
digitizer-workflow doesn't work with more than 9 tpc-lanes

### ISSUE THREAD

**Issue by KlewinS** [AliceO2Group/AliceO2#1222]
I just tried the digitizer-workflow and apparently with more then 9 tpc-lanes it doesn't work any more.

`digitizer-workflow -b --tpc-lanes=9`
seems to work
`digitizer-workflow -b --tpc-lanes=10` 
doesn't work anymore, the same for even more lanes.

output-logs are here:
[log_09lanes.txt](https://github.com/AliceO2Group/AliceO2/files/2115284/log_09lanes.txt)
[log_10lanes.txt](https://github.com/AliceO2Group/AliceO2/files/2115285/log_10lanes.txt)

**Comment by sawenzel** [comment]
How much memory and how many CPU cores do you have? Each digitizer process needs a lot of memory (since we essentially instantiate all "pixels x timebin" dimensions for each sector). It is not recommended to go beyond the number of (physical) cores on your system which is the default.

If you believe this is not due to limited memory, we need to investigate further.

**Comment by KlewinS** [comment]
256 GB of memory and 24 cores, far above the limits

**Comment by sawenzel** [comment]
Good to know. Could be a deadlock? Other people have reported some "hangs" as well. Don't have a good feeling where this could come from but I will try to investigate.

How repeatable is your observation?

**Comment by KlewinS** [comment]
I can run it as often as you want ;-)
I didn't tried to recompile yet, but always if I set the tpc-lanes higher than 9, I run into the same behaviour.

**Comment by KlewinS** [comment]
Sorry, to be a bit more specific: so far, when I tried with less then 10 lanes it always worked, and with 10 or more it always endet in this infinite loop with 0 input and 0 output data. But I just made a few samplings of let’s say around 10 times with more or less random lanes.

If you want, I can try it tomorrow again more systematic.

**Comment by KlewinS** [comment]
I have a suspicion, or at least an idea in which direction you could try to investigate.

Somehow, if I start the digitizer-workflow, there are 3 more processes started than the number of lanes  I enter. So with 9 lanes, there are 12 processes started, which works (and everything below). With 10 lanes, 13 processes are started which doesn't work.

My machine has 2 physical CPUs with 12 cores each, could this be the reason?

**Comment by sawenzel** [comment]
@KlewinS : There is now an improved version of the digitizer-workflow. Would you be able to check if with the new version you still observe the problems above?
