### ISSUE TITLE
Also include `+#include <FairRootManager.h>`

### ISSUE THREAD

**Issue by cholmcc** [AliceO2Group/AliceO2#12396]
https://github.com/AliceO2Group/AliceO2/blob/efe84cb78f0e72da74104dfb09d09edd9e7403b7/Detectors/ITSMFT/test/HitAnalysis/src/HitAnalysis.cxx#L23

The header `FairRootManager.h` should be included.

**Comment by harshitvarma638** [comment]
can you assign me this issue. It would be my first open source contribution.
Will there be any possible confilcts after adding the FairRootManager.h header file in the program.

**Comment by cholmcc** [comment]
Hi,

On 2023-12-18 15:43, PINNAMARAJU HARSHITH VARMA wrote:
> can you assign me this issue. It would be my first open source
> contribution.
> Will there be any possible confilcts after adding the
> FairRootManager.h header file in the program.

I do not have the permissions to assign issues to users.

Yours,

-- 
Christian Holm Christensen 
-------------------------------------------------
  Niels Bohr Institute, Blegdamsvej 17, DK-2100 Copenhagen
  http://cern.ch/cholm, +4524618591

**Comment by shahor02** [comment]
I think the git issues are usually not followed, we either use jira or pull requests. Could you simply open a PR?
