### ISSUE TITLE
Target "HMPIDBase" links to itself

### ISSUE THREAD

**Issue by aphecetche** [AliceO2Group/AliceO2#1243]
Just updated to latest dev and got this warning : 

[cmake] Configuring done
[cmake] CMake Warning (dev) at cmake/O2Utils.cmake:271 (Add_Library):
[cmake]   Policy CMP0038 is not set: Targets may not link directly to themselves.
[cmake]   Run "cmake --help-policy CMP0038" for policy details.  Use the cmake_policy
[cmake]   command to set the policy and suppress this warning.
[cmake] 
[cmake]   Target "HMPIDBase" links to itself.
[cmake] Call Stack (most recent call first):
[cmake]   Detectors/HMPID/base/CMakeLists.txt:16 (O2_GENERATE_LIBRARY)
[cmake] This warning is for project developers.  Use -Wno-dev to suppress it.
[cmake] 
[cmake] Generating done

I guess it was introduced in https://github.com/AliceO2Group/AliceO2/pull/1231

**Comment by sawenzel** [comment]
Fixed.
