### ISSUE TITLE
Use patched ROOT for O2

### ISSUE THREAD

**Issue by shahor02** [AliceO2Group/AliceO2#1245]
Hi,

Can we use patched version of ROOT in O2? Rootcling had a bug preventing proper rootmap creation for certain templates (details in https://root-forum.cern.ch/t/template-forward-declaration-is-missing-in-the-rootmap/29495). As a result the CI test of my PR https://github.com/AliceO2Group/AliceO2/pull/1218  was failing since the macros in interpreter mode could not autoload needed libraries. The problem is now fixed in the ROOT master : https://github.com/root-project/root/pull/2272

Cheers,
 Ruben

**Comment by dberzano** [comment]
Yes, we need to bump ROOT 6 for analysis as well, so, incidentally, there is some ongoing work already. See alisw/alidist#1212 and let's continue the discussion there.
