### ISSUE TITLE
Set C++ standard to at least 20 - 

### ISSUE THREAD

**Issue by cholmcc** [AliceO2Group/AliceO2#12732]
https://github.com/AliceO2Group/AliceO2/blob/2ef03d0b663f8d99f60fec4f5e73cc6fde32e6f3/CMakeLists.txt#L40

Recent changes in the code base _mandates_ that C++ 20 is used, and this should be set in the top-level `CMakeLists.txt` in the referenced line.

**Comment by ktf** [comment]
Let's continue in https://github.com/AliceO2Group/AliceO2/pull/12778 .
