### ISSUE TITLE
GitHub actions are using unavailable `hub` commands

### ISSUE THREAD

**Issue by vkucera** [AliceO2Group/AliceO2#13300]
GitHub action workflows `reports.yml` and `datamodel-doc.yml` use the command `hub pull-request` for creating a PR.
This step has been failing because `hub` is no longer available by default as it was removed in October 2023 (see https://github.com/actions/runner-images/issues/8362).
The `hub pull-request` command should be replaced by the [`gh pr create`](https://cli.github.com/manual/gh_pr_create) command using the GitHub CLI.

**Comment by ktf** [comment]
@singiamtel can you have a look?
