### ISSUE TITLE
Common/Header/AliceO2Config.h generated in source directory

### ISSUE THREAD

**Issue by ktf** [AliceO2Group/AliceO2#135]
Looks like `${CMAKE_CURRENT_SOURCE_DIR}/Common/Header/AliceO2Config.h` is automatically generated in the source directory. This should probably be avoided in favour of generating it in the ${CMAKE_CURRENT_BUILD_DIR} and picking it up from there, otherwise it might break out of source builds.

**Comment by kouzinopoulos** [comment]
Fixed with the latest commits in dev, this issue can be marked as resolved
