### ISSUE TITLE
The O2_GENERATE_LIBRARY macro unsets variables passed to it

### ISSUE THREAD

**Issue by kouzinopoulos** [AliceO2Group/AliceO2#149]
It looks like the O2_GENERATE_LIBRARY macro is unsetting the variables passed to it, including the LIBRARY_NAME variable.

This is confusing behavior and creates the need for hacks, like for example in Examples/flp2epn/CMakeLists.txt.

**Comment by kouzinopoulos** [comment]
Same hack present in the following CMakeLists.txt:

CCDB/CMakeLists.txt
Examples/ExampleModule1/CMakeLists.txt
Examples/ExampleModule2/CMakeLists.txt
Examples/flp2epn/CMakeLists.txt
Examples/flp2epn-distributed/CMakeLists.txt
Utilities/aliceHLTwrapper/CMakeLists.txt
Utilities/QC/QCProducer/CMakeLists.txt
Utilities/QC/QCViewer/CMakeLists.txt
Utilities/QC/QCMerger/CMakeLists.txt

**Comment by MohammadAlTurany** [comment]
Hallo @Barthelemy
Could you check this!
best,
Mohammad

**Comment by Barthelemy** [comment]
Hi, 
Yes, I agree and I don't like it either. I copied the macros from FairRoot and it is one thing I wanted to change. Could you create a ticket in JIRA ? for example in this project : https://alice.its.cern.ch/jira/projects/OCCF
Mohammad, I think that we should disable the issues in github to avoid confusion. I did not notice this issue for several months (shame on me!). All the other ALICE development is followed up in JIRA here : alice.its.cern.ch

**Comment by kouzinopoulos** [comment]
Hello Barth,

I've opened this issue in JIRA: https://alice.its.cern.ch/jira/projects/OCCF/issues/OCCF-9. I didn't know that we were using JIRA for issues/discussion, maybe it should be communicated/reminded again to the rest of the group too?

Cheers,

Charis
________________________________________

**Comment by Barthelemy** [comment]
Hi, 
Thank you !
You are absolutely correct. I will maybe circulate an email on the cwg-all mailing list and remind people in the next plenary. 
Cheers,
Barth

**Comment by sawenzel** [comment]
Is anyone working on this?

**Comment by Barthelemy** [comment]
nope, this is based on the FairRoot cmake macros. I was waiting for FairRoot to migrate to ROOT cmake macros (@Mohammad was working on that at some point) before switching our stuff as well.

**Comment by Barthelemy** [comment]
I was late, you fixed it :+1: thanks !

**Comment by sawenzel** [comment]
Merged into dev. Closing.
