### ISSUE TITLE
alibuild failed in alidock (cmodules/timer.h)

### ISSUE THREAD

**Issue by frmanso** [AliceO2Group/AliceO2#1666]
Hello,
  Since friday, I cannot build aliceo2 inside alidock. The error seems to come from missing cmodules/timer.h related to TPC.
See the log file 
[log.txt](https://github.com/AliceO2Group/AliceO2/files/2827504/log.txt)

**Comment by davidrohr** [comment]
Hi,
do you know what you changed since Friday? AliTPCCommon hasn't changed for quite a while, and I am also wondering why the CI doesn't see it.

**Comment by frmanso** [comment]
In fact, I changed nothing... I'm starting from a fresh installation inside alidock executing:
alidock
aliBuild init O2  --defaults o2
aliBuild build O2 --defaults o2
See the results of the 2 first commands:

manso@clraliceport15:~/alidock$ alidock
Creating container, hold on
Starting a shell into the container
[alidock] ~ $> aliBuild init O2  --defaults o2
remote: Enumerating objects: 35, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 5747 (delta 19), reused 19 (delta 9), pack-reused 5712
Receiving objects: 100% (5747/5747), 1.38 MiB | 0 bytes/s, done.
Resolving deltas: 100% (3710/3710), done.
Note: checking out '6c1ff65e6ca6225420154f3f78f298b1adce1bdd'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

==> Development directory . created for o2

**Comment by frmanso** [comment]
Hello, the issue is coming from the init: 
I used "aliBuild init O2 --defaults o2"  (the usual command since last week) instead of "aliBuild init O2@dev --defaults o2".
If we are not directly inform of this new "small" modification, we spend time to found that one line is changed in the tutorial.
