### ISSUE TITLE
uint64_t : (unsigned long) vs (unsigned long long) ?

### ISSUE THREAD

**Issue by shahor02** [AliceO2Group/AliceO2#1776]
Hi,
Could one of the experts suggest on this problem:

on ubuntu (gcc 7.3.0) the following warning is produced:
````
uint64_t x=0;
printf("%llu\n", x);
            ~~~~  ^~
            %lu
...warning: format specifies type 'unsigned long long' but the argument has type 'uint64_t' (aka 'unsigned long') [-Wformat]
````

on the macOS the opposite:
````
uint64_t x=0;
printf("%lu\n", x);
            ~~~~  ^~
            %llu
...error: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Werror,-Wformat]
````

So, it looks like the macos compiled uses 32bit words while gcc: 64 bits. This makes my PR to fail: https://github.com/AliceO2Group/AliceO2/pull/1753#issuecomment-470671515

Is there a way to calm down the code checker (other than avoiding formatted outputs or using casts) ?

**Comment by davidrohr** [comment]
Hi @shahor02 : The size of int, long, long long is actually compiler-specific.
On gcc, long and long long are both 64 bit, but they are different types.
It seems, uint64_t is defined as unsigned long on the one architecture and as unsigned long long on the other.

There are two ways to circumvent your problem.

1. Just cast it within the printf to the larger type:
printf("%llu}\n", (unsigned long long int) x);

2. Disable compiler warnings for the line (just for reference, I would go with 1.)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wformat"
    [CODE}         /* no warning for this one */
#pragma GCC diagnostic pop

Cheers, David

**Comment by shahor02** [comment]
@david: Thanks! I hoped there will be more elegant methods than casts.  Did not know about these ``#pragma's`` but I agree it is even more clumsy than the casts.

**Comment by davidrohr** [comment]
well,you can use std::cout if you want to be type-independant.
Kind Regards
David Rohr

(Sent from my mobile, excuse the typos.)

**Comment by shahor02** [comment]
Already resorted to cast...
