### ISSUE TITLE
Installation fails due to missing config/mft-dds.json file

### ISSUE THREAD

**Issue by kouzinopoulos** [AliceO2Group/AliceO2#181]
Building O2 fails since commit e21ee97aaec60cb08afa70fc7ff105a3d2146690 due to absence of file config/mft-dds.json from tree, as referenced by file Detectors/ITSMFT/MFT/reconstruction/CMakeLists.txt:

DEBUG:O2:0: CMake Error at Detectors/ITSMFT/MFT/reconstruction/cmake_install.cmake:187 (file):
DEBUG:O2:0:   file INSTALL cannot find
DEBUG:O2:0:   "/opt/alice/sw/SOURCES/O2/master/0/Detectors/ITSMFT/MFT/reconstruction/config/mft-dds.json"

@MohammadAlTurany @bovulpes

**Comment by bovulpes** [comment]
In my last commit, in "Detectors/ITSMFT/MFT/reconstruction/config" I put a file with the name "reco.json", I don't know what  "mft-dds.json" is.

**Comment by ktf** [comment]
I've the same issue here, actually. I fixed it by simply dropping it.

**Comment by ktf** [comment]
See also #184

**Comment by kouzinopoulos** [comment]
Work around provided by commit 14e18dcd505a966eec301fb15f796ba670651410
