### ISSUE TITLE
Compilation error in AliceO2 

### ISSUE THREAD

**Issue by Hushnud15** [AliceO2Group/AliceO2#183]
I have successfully installed the ALFA, FAIRROOT, Aliroot and DDS. During complitation AliceO2 I got the following error.
/home/hushnud/Desktop/My_Alice_O2/O2/Utilities/aliceHLTwrapper/src/aliceHLTEventSampler.cxx: In function ‘int sendSocketPropertiesDDS(std::vector<SocketProperties_t>&)’:
/home/hushnud/Desktop/My_Alice_O2/O2/Utilities/aliceHLTwrapper/src/aliceHLTEventSampler.cxx:520:34: error: no matching function for call to ‘dds::intercom_api::CKeyValue::CKeyValue()’
     dds::intercom_api::CKeyValue ddsKeyValue;
                                  ^
/home/hushnud/Desktop/My_Alice_O2/O2/Utilities/aliceHLTwrapper/src/aliceHLTEventSampler.cxx:520:34: note: candidates are:
In file included from /home/hushnud/Desktop/My_Alice_O2/O2/Utilities/aliceHLTwrapper/src/aliceHLTEventSampler.cxx:36:0:
/home/hushnud/Desktop/My_Alice_O2/ALFA/DDS/include/dds_intercom.h:59:13: note: dds::intercom_api::CKeyValue::CKeyValue(dds::intercom_api::CIntercomService&)
             CKeyValue(CIntercomService& _service);
             ^
/home/hushnud/Desktop/My_Alice_O2/ALFA/DDS/include/dds_intercom.h:59:13: note:   candidate expects 1 argument, 0 provided
/home/hushnud/Desktop/My_Alice_O2/ALFA/DDS/include/dds_intercom.h:46:15: note: constexpr dds::intercom_api::CKeyValue::CKeyValue(const dds::intercom_api::CKeyValue&)
         class CKeyValue
/home/hushnud/Desktop/My_Alice_O2/O2/Utilities/aliceHLTwrapper/src/aliceHLTEventSampler.cxx:549:85: note:   candidate expects 2 arguments, 3 provided
make[2]: *** [Utilities/aliceHLTwrapper/CMakeFiles/aliceHLTEventSampler.dir/src/aliceHLTEventSampler.cxx.o] Error 1
make[1]: *** [Utilities/aliceHLTwrapper/CMakeFiles/aliceHLTEventSampler.dir/all] Error 2
make: *** [all] Error 2

**Comment by MohammadAlTurany** [comment]
Hallo,

This is due to the change of the API in DDS, @matthiasrichter  could you please update the aliceHLTwrapper?

For now you can exclude the aliceHLTwrapper package from the build by committing out the line:

add_subdirectory (aliceHLTwrapper)

in the file 
/home/hushnud/Desktop/My_Alice_O2/O2/Utilities/CMakeLists.txt

best,
Mohammad

**Comment by matthiasrichter** [comment]
Hi Mohammad,
I spend a lot of time now to get an installation with DDS, but although using the latest alibuild and alidist, O2 cmake configuration reports that DDS is not found. Despite the fact that DDS is a dependency for both FairRoot and O2 and that it is even installed. So I have no clue what has been changed in the API. In principle changes in the API should be made backward compatible after the first release of the package. Can you pick this up with the DDS guys?

Cheers
Matthias

**Comment by ktf** [comment]
We can close this, right?

**Comment by matthiasrichter** [comment]
I have started to adjust the code to the FairMQ API. I kept the issue open because the it is not really fixed, only the compilation does not break any more
