### ISSUE TITLE
Linking error in DataFormats/Headers/

### ISSUE THREAD

**Issue by kouzinopoulos** [AliceO2Group/AliceO2#211]
When building a fresh copy of O2 using alibuild, i get the following linking error:

```
DEBUG:O2:0: CMakeFiles/fairMQmonitor.dir/src/FairMQmonitor.cxx.o: In function `AliceO2::Header::Block::freefn(void*, void*)':
DEBUG:O2:0: /opt/alice/sw/SOURCES/O2/dev/0/DataFormats/Headers/include/Headers/DataHeader.h:301: undefined reference to `AliceO2::Header::Block::sDeleter'
DEBUG:O2:0: collect2: error: ld returned 1 exit status
```

Ubuntu 14.04.5
GCC 4.8.4
Alidist branch IB/v5-08/o2

@mkrzewic

**Comment by mkrzewic** [comment]
Hi, the compiler might be a bit too old ;) Can you pull from my dev-dataformat branch and try again?

**Comment by kouzinopoulos** [comment]
Built against gcc 5.4.0, it compiles/links ok. If 4.8.x is not supported i will close the bug report

**Comment by mkrzewic** [comment]
the problem was a missing definition which apparently is handled gracefully in more recent compilers. Already fixed in my branch, i'll make a pull request, so i think it can be closed.

**Comment by rbx** [comment]
Just for the record, I had this error also with GCC 6.2.0. The fix from your branch helped.

**Comment by mkrzewic** [comment]
gcc 4.8.5 and llvm 7.3 did not complain, but i've seen that disagreement between compilers is not that uncommon. closing.

**Comment by mkrzewic** [comment]
..or rather - @kouzinopoulos can you close?
