### ISSUE TITLE
includes in header files not found

### ISSUE THREAD

**Issue by wiechula** [AliceO2Group/AliceO2#219]
Dear all,

if I try in a header file from TPCSimulation to include a hader from TPCBase:
#include "TPCBase/PadSecPos.h"

I get:
input_line_12:1480:10: fatal error: 'TPCBase/PadSecPos.h' file not found
#include "TPCBase/PadSecPos.h"

If the include statement is in the source file it works. If the include statement is in the header of the same component it also works.

Thanks in advance for any hint.

Cheers,
Jens

**Comment by wiechula** [comment]
Hmm, seems I found a (preliminary) solution, also perhaps not the foreseen one.

I added
${CMAKE_SOURCE_DIR}/Detectors/TPC/base/include
to the 
INCLUDE_DIRECTORIES
statement of
tpc_simulation_bucket
in
cmake/O2Dependencies.cmake

**Comment by Barthelemy** [comment]
Hi, 
Sorry for the very late reply. You are correct, the include directory of the other component should be added. Not the most straightforward maybe. Hopefully we will find a way to add it transparently. 
Cheers,

**Comment by Barthelemy** [comment]
Apparently I can't close this issue. Anyone could please ?

**Comment by wiechula** [comment]
I think it would be good to have some kind of documentation how this is foreseen to be done and best also the philosophy behind the CMake files

**Comment by Barthelemy** [comment]
Correct. I had started something. I should finish it. Here it is : https://github.com/AliceO2Group/AliceO2/blob/dev/docs/doxygen/CodeOrganization.md

In general documentation is problematic at the moment. The doxygen does not easily build and is not in sync online. There is a JIRA for this : https://alice.its.cern.ch/jira/browse/OCCF-15
