### ISSUE TITLE
Clarification of O2device class

### ISSUE THREAD

**Issue by sawenzel** [AliceO2Group/AliceO2#233]
Upon review of some parts of the code (with @ktf and @matthiasrichter), the following questions came up:

a) what is the purpose of the class `O2device`? It seems to offer only static (standalone) functions. None of the functions is modyfying/accessing any member variable.

In this sense, would it make sense to just offer standalone functions in a utility namespace?

b) the name `O2device` reads strange. According to our naming conventions, I believe it should be `O2Device`. 

Note: Instead of commenting on code, I am opening an issue to facilitate the discussion and have easier follow up.

**Comment by mkrzewic** [comment]
Hi,
The purpose is:
 - currently: to simplify the API. The AddMessage() method is not static, it uses FairMQ functionality, a standalone version would have to pass an additional parameter (something like "this" or a pointer/ref to a transport factory).

- in general: this would be a place to implement any other (subtle) differences to FairMQ which might (and most probably will) pop up in the future in a way completely transparent to the (O2-) devices.

That being said, I was also initially opposed to having an O2Device class until I started playing with the code - this seems a tad more elegant and simple.

**Comment by sawenzel** [comment]
@mkrzewic:

a) Thanks. Indeed the `NewMessage` member function is called so I understand the reasoning.

b) The class name should still be fixed.

**Comment by mkrzewic** [comment]
done, #234
