### ISSUE TITLE
Change `AliceO2::` namespace to `O2::` or `o2::`

### ISSUE THREAD

**Issue by ktf** [AliceO2Group/AliceO2#239]
I would propose we change the namespace `AliceO2` to `O2` or even `o2` given there is little value in the long name, just extra typing. I would also propose that anything O2 specific is simply put in the O2 namespace, and does not have the O2 prefix. For example things like O2Message and O2Device should really be `o2::Message` or `o2::Device`.

**Comment by ktf** [comment]
For CWG11 discussion.

**Comment by Barthelemy** [comment]
Added to https://alice.its.cern.ch/jira/browse/OCCF-24

**Comment by dberzano** [comment]
Ook seems we've forgot to discuss it. I don't see any reason why not, actually it seems a very good idea to me, and also not controversial. Can we simply carry on, without any further discussion? :-)

**Comment by matthiasrichter** [comment]
Well we would need to discuss whether to use `O2` or `o2`.

Also one should probably announce it and ask developers if they want to merge pending work before this change is applied. And then of course merge pending PRs

**Comment by dberzano** [comment]
@matthiasrichter the thing is that CWG11 is anyway quite restricted and somebody outside the group will miss the "discussion". Is there anybody with a very strong opinion on the subject? I really could not care less about the case!

**Comment by Barthelemy** [comment]
I don't care :)

**Comment by dberzano** [comment]
@sawenzel, @MohammadAlTurany, @mkrzewic do you have any take on the `O2` vs. `o2` matter?

**Comment by sawenzel** [comment]
If our conventions don't tell otherwise, I generally prefer lower case letters for namespaces. Hence I would got for "o2".

**Comment by ktf** [comment]
I'd prefer o2 as well.

**Comment by MohammadAlTurany** [comment]
both fine for me!

**Comment by matthiasrichter** [comment]
I have a slight preference for upper case. It will probably be more consistent with other namespace names like e.g. for the detectors. There we would probably stick to upper case. And we use camel case anyhow, so `DataFlow` might take precedence over `dataflow` as namespace name.

Using lower case would also imply to change others to lower case as well, e.g. `Header` -> `header`

On my own personal take, `O2::Header::DataHeader` fits my eyes better than `o2::Headers::DataHeader` or `o2::header::DataHeader`.

**Comment by mkrzewic** [comment]
I have no strong opinion on the case (o2/O2) - both are fine for me.

**Comment by ktf** [comment]
The rationale for having lowercase namespace names would be to distinguish them from class scopes. I.e.:

```
o2::header::DataHeader::get
^   ^       ^          ^----- lowercase after upper case: method
|   |       \-----uppercase: class name
|   \------lowercase: namespace
\------lowercase: namespace
```

**Comment by sawenzel** [comment]
This is also my rational. namespace lowercase. Classes/Types uppercase.

**Comment by matthiasrichter** [comment]
fine with me

**Comment by ktf** [comment]
@sawenzel made me notice that this is actually different from what we have in the coding conventions:

https://htmlpreview.github.io/?https://github.com/AliceO2Group/CodingGuidelines/blob/master/naming_formatting.html#Namespace_Names

@Barthelemy @dberzano what is the procedure to change them? Shall I just open a PR?

**Comment by Barthelemy** [comment]
@ktf I think that if there is an agreement in CWG11 (on the mailing list or in a meeting) one should simply open a PR.

**Comment by Barthelemy** [comment]
(I think that there is an agreement in the mailing list in this particular case)

**Comment by sawenzel** [comment]
done
