### ISSUE TITLE
Check correct sizing of strings for DataDescription

### ISSUE THREAD

**Issue by sawenzel** [AliceO2Group/AliceO2#240]
The AliceO2::Header::DataDescription constructor should check that the ("constexpr") input string is actually not longer than the allowed size

**Comment by matthiasrichter** [comment]
ok,will fix this. good point

**Comment by sawenzel** [comment]
I already fixed it locally in the following way:

```c++
 DataDescription(const char *desc) : itg{String2uint64(desc),String2uint64(desc,8)} {
    assert(strlen(desc)<gSizeDataDescriptionString);
  }
```

that is taking away the `constexpr` and using runtime assert. The constexpr does not make much sense (since you assign anyway runtime conf strings).

The alternative would be to offer something like 
```c++
template <size_t N> 
DataDescription(const char & desc[N]) : itg{String2uint64(desc),String2uint64(desc,8)} {
    static_assert(N < 16);
  }
```
which should work for the compile time known strings.

**Comment by mkrzewic** [comment]
The idea was to do everything at compile time. But I also wanted to have some way of checking that user data formats use unique identifiers - so far I have not found a way to do this at compile time. Maybe constructing those at runtime would make the check it easier - it could fail fast at library load in case someone tries to declare an ID that already exists. But still, maybe there is a way to do this at compile time...

**Comment by sawenzel** [comment]
Actually some other questions come up here:

Are we supposed to have completely fixed-time strings? In principle, we were happily using constructs like 
`DataDescription("FOO")` which worked fine often but crashed every now and then because the constructor is trying to access memory further than 3 characters.

As a user, I would prefer not having to type
`DataDescription("FOO__________");`

I added a proper unit test that shows this strange behaviour and will ask for a pull-request.

**Comment by ktf** [comment]
+1 for the fact that we should not mandate space padded strings in the User
API. I.e. internally you can do that, but the constructor should be smart
enough to do the padding itself.

**Comment by mkrzewic** [comment]
The original implementation did pad shorter strings with null chars. Something changed?

**Comment by matthiasrichter** [comment]
I had the templated version in mind to make sure that we use compile time assert. The only purpose is to define compile time constants which can be used throughout the program. There is no need to process runtime strings. For all runtime operations, the internal integer is used.

I have to check if I destroyed the padding in commit 43d7eda05aea22c358887f7400b5dc8c1f8d0b23. Clearly we do not want the user to pad with spaces, that was never the intention

**Comment by matthiasrichter** [comment]
I have now cleaned up the patch and pushed it to my fork, please have a look
https://github.com/matthiasrichter/AliceO2/commit/35a998d921bb5404cd9477efe89d2e799bf9e5de

I'm extending the unit test now to catch all the use cases.

**Comment by matthiasrichter** [comment]
ok, I also caught the occasional problem with the description strings shorter than 16. Actually it happens when the string is shorter than 8 because `String2<uint64_t>` is called two times, the second time with an offset of 8. This call is missing the correct length check. I will include the fix in my patch.

**Comment by matthiasrichter** [comment]
ok, I also caught the occasional problem with the description strings shorter than 16. Actually it happens when the string is shorter than 8 because `String2<uint64_t>` is called two times, the second time with an offset of 8. This call is missing the correct length check. I will include the fix in my patch.

**Comment by matthiasrichter** [comment]
I have to wait for PR #237 to be merged before pushing further updates
