### ISSUE TITLE
Mismatch between `AliceO2::Header::get(byte *)` and `void *FairMQMessage::GetData`

### ISSUE THREAD

**Issue by ktf** [AliceO2Group/AliceO2#243]
Some compilers seems to complain about the implicit cast which happens when you do:

```
AliceO2::Header::get<DataHeader>(message->GetData())
```

in order to get it to work I need to make it explicit:

```
AliceO2::Header::get<DataHeader>((byte *)message->GetData())
```

Can we align the API to the FairRoot one?

**Comment by ktf** [comment]
or change the FairMQ one, of course. @matthiasrichter @mkrzewic @MohammadAlTurany @rbx

**Comment by mkrzewic** [comment]
for buffers (always containing byte arrays) I prefer to be explicit and use byte* - a void* in my opinion means something else. I think the reason GetData() returns void* is because zeromq/nanomsg do that (since they present a C API), so it is kinda historic. I'd prefer to change the FairMQ one if there are no strong reasons against.

**Comment by ktf** [comment]
I agree changing `fairmq` is probably better, however I guess that's FairRoot team call. @rbx / @MohammadAlTurany?

**Comment by rbx** [comment]
Your solution is the best (perhaps with a static_cast though):
```C++
AliceO2::Header::get<DataHeader>((byte *)message->GetData())
```
Although changing FairMQ interface to byte/unsigned char would work, it is less correct.
FairMQ doesn't know what is inside the message, thus void* is the correct type. Making it char/unsigned char/signed char would be misleading. It would also open up room for error, by allowing pointer arithmetic on the returned pointer - returning void* prevents this. That's why void*, that you cast to the type you need.

What I could try is to make a templated GetData, e.g. so you can call GetData<byte*>(), that would save you the cast, but still specify the type.

**Comment by ktf** [comment]
I think `GetData<byte*>()` is as good as `(byte *)GetData()`, so IMHO is not a solution. Given also that you might want to call some C function (e.g. memcpy, memove) on the buffer, I guess my preference is for `void* GetData()` as it is now, and then we wrap it to (byte*) in the O2 specific code (since in any case `byte` is a O2 specific type). @mkrzewic what would you consider a `void*`?

**Comment by mkrzewic** [comment]
@ktf to me a void* is a pointer to an **object** of unknown type. In the case of the message we know the type of thing: it is a byte array. I think the old C (void*) conventions are still a bit entangled with the new one (C++11 memory model) where memory (or a buffer) is a sequence of bytes (<unsigned> char = byte).
As for the usage of memcpy: shouldn't we rather be using std::copy? as for memmove etc using teh old C API with void* to represent memory we should wither avoid(?) or at least treat with care.

**Comment by mkrzewic** [comment]
I think in general the use of void* in C++ is being discouraged, at least for representing buffers. Even GSL (the guideline support library spec) defines a byte type for use with buffers - it then makes for an easier transition into the new stuff like array views etc. I agree it is a matter of taste - but for new code i lean towards more modern approaches, hence the introduction and the use of the byte typedef in the o2 namespace.

**Comment by ktf** [comment]
Well, in this particular case the fact that we (O2) interpret it as a `byte*` is actually our own design decision. If I understand correctly, fairmq is actually agnostic to that and in principle one of the experiments they want to serve might decide that for them all the parts are (for instance) flatbuf serialised objects (which they support in a separate layer, if I understand correctly) at that point `void *` is a more appropriate, generic API, IMHO. Moreover they would probably use `char *` rather than `byte *`, since the latter is really our own (perfectly valid, but non-standard) typedef, which would add confusion. I think it's still better if we change our code*, especially since the FairRoot folks expressed preference for keeping the `void*`.

*: To be clear, I mean changing it so that we take both "char *" and "void *", internally doing the cast to the former in case of the latter, rather than in the user code.

**Comment by mkrzewic** [comment]
yes, I agree, I'm not trying to push for changes in fairmq (in this case ;)), we can do the cast to whatever o2 convention.
Aside from that - I cannot resist making a slightly philosophical note: no matter what travels in the buffer, for fairmq it looks like a pointer to start of the buffer and a length, both things are needed to describe a buffer. So if we have a void* buf and a size_t len - what does it mean? That we have len elements of type void? Len in fairmq is in bytes (not number of elements, which does not make sense in case of void anyway), so it makes more sense (to me) to have byte* buf, size_t len as it is more expressive. Additionally, no matter what you have in there - a static cast should not work, ever, that is too high level an abstraction, you are not dealing with any type in fact, it is an externally produced buffer. If you get a buffer, you have to reinterpret_cast somewhere to express the intent: you essentially are hoping that you know how to (re-)interpret the sequence of bits.

**Comment by ktf** [comment]
Ok. I've done the work to support both void * and char * in #260. I am closing this and we continue discussion there, if needed.
