### ISSUE TITLE
O2_GENERATE_DICTIONARY problem when Headers are not set explicitely

### ISSUE THREAD

**Issue by sawenzel** [AliceO2Group/AliceO2#249]
I ran into the following problem:

a) I do not set HEADERS explicitely in my cmake
b) I set LINKDEF to some LinkDef.h

Since HEADERS are not set, `O2_GENERATE_LIBRARY` will search for HEADERS itself and picks up `LinkDef.h`. This leads to errors with rootcling because "LinkDef.h" will appear twice.

I think we need to protect against this in some way. Possibly just checking if the LINKDEF file is also present in the HEADERS list.

**Comment by Barthelemy** [comment]
You are correct. I'll have a look.

**Comment by ktf** [comment]
Is this done?

**Comment by Barthelemy** [comment]
no. I will move it to JIRA where I will be able to see it and organize it with the rest of my work. How can I close this one ? There is no close button.

**Comment by Barthelemy** [comment]
https://alice.its.cern.ch/jira/browse/OCCF-46

**Comment by sawenzel** [comment]
@Barthelemy: I think the issue should stay open here in parallel. Otherwise, it is hard to track progress and know when it was done ...

**Comment by Barthelemy** [comment]
@sawenzel I understand your point. At the same time, I fear that it will quickly become unmanageable. I will keep it opened for now but would like to rediscuss it with you after Christmas, maybe around a coffee.

**Comment by sawenzel** [comment]
Agreed.
