### ISSUE TITLE
Array out-of-bounds warning in DataHeader.h

### ISSUE THREAD

**Issue by sawenzel** [AliceO2Group/AliceO2#268]
I see the following warning, which probably needs to be fixed or silenced:

In file included from /Users/swenzel/git/sw/SOURCES/O2/0_O2_DAQ/0/DataFormats/Headers/test/dataHeaderTest.cxx:5:
/Users/swenzel/git/sw/SOURCES/O2/0_O2_DAQ/0/DataFormats/Headers/include/Headers/DataHeader.h:200:11: warning: array index 7 is past the end of the array
      (which contains 7 elements) [-Warray-bounds]
         (str[1+pos] && sizeof(T) >= 4 ? ((T) str[2+pos] << (sizeof(T) >= 4 ? 16 : 0) |

**Comment by matthiasrichter** [comment]
I don't see it in my setup, what's your compiler version? Is there more information in the log, I would be interested in the line number with the code which triggers this (line 5 is just the include of the header)

**Comment by sawenzel** [comment]
I'll take a look concerning the exact line. It is the clang compiler on MacOS 10.11.

**Comment by sawenzel** [comment]
Here is the full log:

In file included from /Users/swenzel/git/sw/SOURCES/O2/0_O2_DAQ/0/DataFormats/Headers/test/dataHeaderTest.cxx:5:
/Users/swenzel/git/sw/SOURCES/O2/0_O2_DAQ/0/DataFormats/Headers/include/Headers/DataHeader.h:200:11: warning: array index 7 is past the end of the array
      (which contains 7 elements) [-Warray-bounds]
         (str[1+pos] && sizeof(T) >= 4 ? ((T) str[2+pos] << (sizeof(T) >= 4 ? 16 : 0) |
          ^   ~~~~~
/Users/swenzel/git/sw/SOURCES/O2/0_O2_DAQ/0/DataFormats/Headers/include/Headers/DataHeader.h:576:130: note: in instantiation of function template specialization
      'AliceO2::Header::String2<unsigned long long, 7, 6, false>' requested here
  constexpr DataDescription(const char (&desc)[NN]) : itg{String2<uint64_t, NN, 0, true>(desc), (Internal::strLength(desc) > 8 ? String2<uint64_t, NN, std::conditiona...
                                                                                                                                 ^
/Users/swenzel/git/sw/SOURCES/O2/0_O2_DAQ/0/DataFormats/Headers/test/dataHeaderTest.cxx:60:23: note: in instantiation of function template specialization
      'AliceO2::Header::DataDescription::DataDescription<7>' requested here
      DataDescription desc("ITSRAW");
                      ^
/Users/swenzel/git/sw/SOURCES/O2/0_O2_DAQ/0/DataFormats/Headers/include/Headers/DataHeader.h:191:21: note: array 'str' declared here
constexpr T String2(const char (&str)[N])
                    ^
/Users/swenzel/git/sw/SOURCES/O2/0_O2_DAQ/0/DataFormats/Headers/include/Headers/DataHeader.h:201:11: warning: array index 8 is past the end of the array
      (which contains 7 elements) [-Warray-bounds]
         (str[2+pos] && sizeof(T) >= 4 ? ((T) str[3+pos] << (sizeof(T) >= 4 ? 24 : 0) |
          ^   ~~~~~
/Users/swenzel/git/sw/SOURCES/O2/0_O2_DAQ/0/DataFormats/Headers/include/Headers/DataHeader.h:191:21: note: array 'str' declared here
constexpr T String2(const char (&str)[N])
                    ^
/Users/swenzel/git/sw/SOURCES/O2/0_O2_DAQ/0/DataFormats/Headers/include/Headers/DataHeader.h:202:11: warning: array index 9 is past the end of the array
      (which contains 7 elements) [-Warray-bounds]
         (str[3+pos] && sizeof(T) >= 8 ? ((T) str[4+pos] << (sizeof(T) >= 8 ? 32 : 0) |
          ^   ~~~~~
/Users/swenzel/git/sw/SOURCES/O2/0_O2_DAQ/0/DataFormats/Headers/include/Headers/DataHeader.h:191:21: note: array 'str' declared here
constexpr T String2(const char (&str)[N])
                    ^
/Users/swenzel/git/sw/SOURCES/O2/0_O2_DAQ/0/DataFormats/Headers/include/Headers/DataHeader.h:203:11: warning: array index 10 is past the end of the array
      (which contains 7 elements) [-Warray-bounds]
         (str[4+pos] && sizeof(T) >= 8 ? ((T) str[5+pos] << (sizeof(T) >= 8 ? 40 : 0) |
          ^   ~~~~~
/Users/swenzel/git/sw/SOURCES/O2/0_O2_DAQ/0/DataFormats/Headers/include/Headers/DataHeader.h:191:21: note: array 'str' declared here
constexpr T String2(const char (&str)[N])
                    ^
/Users/swenzel/git/sw/SOURCES/O2/0_O2_DAQ/0/DataFormats/Headers/include/Headers/DataHeader.h:204:11: warning: array index 11 is past the end of the array
      (which contains 7 elements) [-Warray-bounds]
         (str[5+pos] && sizeof(T) >= 8 ? ((T) str[6+pos] << (sizeof(T) >= 8 ? 48 : 0) |
          ^   ~~~~~
/Users/swenzel/git/sw/SOURCES/O2/0_O2_DAQ/0/DataFormats/Headers/include/Headers/DataHeader.h:191:21: note: array 'str' declared here
constexpr T String2(const char (&str)[N])
                    ^
/Users/swenzel/git/sw/SOURCES/O2/0_O2_DAQ/0/DataFormats/Headers/include/Headers/DataHeader.h:205:11: warning: array index 12 is past the end of the array
      (which contains 7 elements) [-Warray-bounds]
         (str[6+pos] && sizeof(T) >= 8 ? ((T) str[7+pos] << (sizeof(T) >= 8 ? 56 : 0) )
          ^   ~~~~~
/Users/swenzel/git/sw/SOURCES/O2/0_O2_DAQ/0/DataFormats/Headers/include/Headers/DataHeader.h:191:21: note: array 'str' declared here
constexpr T String2(const char (&str)[N])
                    ^

**Comment by matthiasrichter** [comment]
It looks like that the different compilers handle the `constexpr` information differently, and in this case a code branch is compiled which is not called in the end. Its in line
https://github.com/AliceO2Group/AliceO2/blob/8339096e9d13a91f46a02026ba62871416b3bbe2/DataFormats/Headers/include/Headers/DataHeader.h#L576

Here the idea is to call the `StringTo` function for the second `itg` element only if the string is longer than 8 characters.

I will implement the functionality on the basis of meta functions instead of constexpr functions.

I would like to test this myself, Giulio (@ktf) is there a simple way to make alibuild using clang toolchain on linux?

@sawenzel which clang version is used in your MacOS 10.1?
