### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by ktf** [AliceO2Group/AliceO2#269]
Since we say we are GPL, we should add a LICENSE file to the project, so that we can make it very clear that any contribution is done under GPL.

@dberzano @Barthelemy

**Comment by Barthelemy** [comment]
Absolutely
There is a related issue here : https://alice.its.cern.ch/jira/browse/OCCF-1

We should really go back to the list of items of CWG11 and tackle them.

**Comment by dberzano** [comment]
@ktf is the LICENSE file the only thing that's needed to make GitHub automatically place the license badge on the repository's home?

**Comment by ktf** [comment]
Let's close this and continue discussion in #283 .
