### ISSUE TITLE
Headers and libraries for Pythia

### ISSUE THREAD

**Issue by bovulpes** [AliceO2Group/AliceO2#270]
Hello,

I know some changes have been recently done with the location of the Pythia related files, but I did not quite get the final conclusion. I tried recently to install the full chain (FairSoft, DDS, FairRoot, AliRoot, AliceO2) and found that in order to eliminate the errors when building AliceO2 I have to do the following (ugly) links by hand:

cd /your_software_dir/external/FairRoot/include
ln -s /your_software_dir/external/include/Pythia8 .

cd /your_software_dir/external/lib
ln -s /your_software_dir/external/AliRoot/lib/libpythia6.so .

(which means I also have to install AliRoot)

Note that I am still using the common installation in the "external" directory. 
Is this correct or am I missing something in the settings?

Thank you.

regards,
Bogdan.

PS: I am not yet using aliBuild to install O2 since I have encountered some problems, there is an issue opened about this here https://github.com/alisw/alibuild/issues/431

**Comment by matthiasrichter** [comment]
Hi Bogdan (@bovulpes),
I believe this issue can be closed. Running cmake for AliceO2 allows to set the switches ` Pythia6_LIBRARY_DIR` and `PYTHIA8_INCLUDE_DIR` which control exactly this. In your workaround you simply added the Pythia include and library to directories already known to the build system. The `o2.sh` recipe for `alibuild` configures those switches. When not using `alibuild` one is required to do this manually.

@sawenzel what puzzles me a bit is the fact that the Pythia8 include directory together with the Pythia6 library is configured in the `o2.sh` recipe. Do you have an idea why it is like that?
https://github.com/alisw/alidist/blob/5657a6f41d6f500da5a9eb8b2b026d1b4b2ad629/o2.sh#L63

**Comment by bovulpes** [comment]
Hi Matthias, 

Ok, things have evolved since, I am closing it.
