### ISSUE TITLE
C++14 feature check in cmake

### ISSUE THREAD

**Issue by mkrzewic** [AliceO2Group/AliceO2#291]
Hi, I have a first version of the feature cehck in cmake in my [branch](https://github.com/mkrzewic/AliceO2/tree/c++14features)

it is shamelessly "inspired" by fairroot, and it works (there are 5 checks in there implemented by Adam), but still cmake is reporting -std=c++11 cflags in the output (as set externally from an alidist recipe). This probably needs to be cleaned up and checked if the flags set by the checks are active later on in the build process. Input is welcome.

DEBUG:O2:0: --- Compiler Flags: -fPIC -g -O2 -std=c++11 -fno-omit-frame-pointer  
DEBUG:O2:0: -- Checking C++14 support for "aggregate-initialization"
DEBUG:O2:0: -- Checking C++14 support for "aggregate-initialization": works
DEBUG:O2:0: -- Checking C++14 support for "binary-literals"
DEBUG:O2:0: -- Checking C++14 support for "binary-literals": works
DEBUG:O2:0: -- Checking C++14 support for "generic-lambda"
DEBUG:O2:0: -- Checking C++14 support for "generic-lambda": works
DEBUG:O2:0: -- Checking C++14 support for "user-defined-literals"
DEBUG:O2:0: -- Checking C++14 support for "user-defined-literals": works

**Comment by Barthelemy** [comment]
Not sure if it fits here, but one should remember that ROOT must be compiled with the --c++14 flag if we want to use c++14 features. This is for alibuild I guess...

**Comment by mkrzewic** [comment]
Hi, the code needed to do the checks is in O2, so in that sense it fits in here. Agreed that more changes will be needed in alidist (compile flags, package versions etc.) as discussed last week.

**Comment by sawenzel** [comment]
This was merged. Can we close the issue?

**Comment by mkrzewic** [comment]
indeed. closing.
