### ISSUE TITLE
Run unit tests during PR checking 

### ISSUE THREAD

**Issue by sawenzel** [AliceO2Group/AliceO2#294]
As a developer I would like that the unit tests are run in the PR - CI.

**Comment by ktf** [comment]
Agreed. alisw/alidist#668 should take care of running them. We should really clean the tests up, as discussed, before we enable the actual testing.

**Comment by matthiasrichter** [comment]
I think the unit test are executed now, this issue can probably be closed

**Comment by sawenzel** [comment]
Ok. It seems to be the case indeed. Closing.
