### ISSUE TITLE
Install header files

### ISSUE THREAD

**Issue by ktf** [AliceO2Group/AliceO2#296]
As a user I need to have header files installed (possibly with make install) in CMAKE_INSTALL_PREFIX so that my macros which refer to them can be run. Unless I am missing something, this is not done at the moment.

**Comment by ktf** [comment]
@dberzano I understand you are doing this. Can you please assign it to yourself, if so?

**Comment by matthiasrichter** [comment]
I actually thought that this is working,at least for the header files in in 'include/${MODULE_NAME}' (the public ones). However, Jens notified me that my commit in #257 has broken, something. I need to have a closer look.
