### ISSUE TITLE
Build system problems

### ISSUE THREAD

**Issue by matthiasrichter** [AliceO2Group/AliceO2#30]
Observed 2 issues:
1) On linux, the linking of executables in make install fails with a message like

    cd /home/richterm/src/AliceO2/matthias.github/build_2015-01-12/devices/aliceHLTwrapper && /usr/bin/cmake -E cmake_link_script CMakeFiles/aliceHLTWrapper.dir/relink.txt --verbose=1
    /usr/bin/c++    -std=c++11 -g -Wshadow     CMakeFiles/aliceHLTWrapper.dir/aliceHLTWrapper.cxx.o  -o CMakeFiles/CMakeRelink.dir/aliceHLTWrapper  -L/home/richterm/src/AliceO2/externals/2015-01-12/FairRoot/lib  -L/home/richterm/src/AliceO2/externals/2015-01-12/lib -rdynamic ../../lib/libALICEHLT.so.0.0.0 -ldl -lboost_thread -lboost_system -lFairMQ
    /usr/bin/ld: warning: libprotobuf.so.8, needed by /home/richterm/src/AliceO2/externals/2015-01-12/FairRoot/lib/libFairMQ.so, not found (try using -rpath or -rpath-link)
    /usr/bin/ld: warning: libzmq.so.3, needed by /home/richterm/src/AliceO2/externals/2015-01-12/FairRoot/lib/libFairMQ.so, not found (try using -rpath or -rpath-link)
    /usr/bin/ld: warning: libboost_timer.so.1.54.0, needed by /home/richterm/src/AliceO2/externals/2015-01-12/FairRoot/lib/libFairMQ.so, not found (try using -rpath or -rpath-link)
    /usr/bin/ld: warning: libboost_program_options.so.1.54.0, needed by /home/richterm/src/AliceO2/externals/2015-01-12/FairRoot/lib/libFairMQ.so, not found (try using -rpath or -rpath-link)
    /home/richterm/src/AliceO2/externals/2015-01-12/FairRoot/lib/libFairMQ.so: undefined reference to `zmq_msg_init'

The linke can't find the runtime libraries which are necessary to solve all symbols in libFairMQ.so, which is properly build.
The problem can be fixed by adding the runtime library path to `$LD_LIBRARY_PATH`, but the build should not depend on that. By adding

    SET(CMAKE_INSTALL_RPATH library_paths)

the issue can be fixed generically as the install directory of external libraries is known. We have to find the best place. probably in the main `CMakeLists.txt`.

2) The variable `AlFa_DIR` is used in several places, but it is not set by the build system

**Comment by matthiasrichter** [comment]
@MohammadAlTurany I don't know how relevant this still is. The first point is probably handled by every module individually. The second point is still valid, we probably should remove AlFa_DIR, I started in my code.

**Comment by MohammadAlTurany** [comment]
Solved!
