### ISSUE TITLE
cannot compile after 1c13762

### ISSUE THREAD

**Issue by wiechula** [AliceO2Group/AliceO2#315]
Dear all,

commit 1c13762 breaks compilation for me. Removing this commit everything works fine. Do I have to update other packages than O2 as well?

Thanks,
Jens

**Comment by sawenzel** [comment]
@wiechula : Do you have the latest FairRoot? Commit 1c13762 needs the latest version of FairRoot.

**Comment by wiechula** [comment]
ok thanks for the info, I'll try that

**Comment by wiechula** [comment]
hmm. the requirement on cmake changed to 3.6.0. I gues this means that I'll have to recomplie all software from scratch, since mainly all packages depend on cmake, right?
So again wait for a few hours. Or is there a way around?
I only need cmake for updating FairRoot and O2 ...
