### ISSUE TITLE
Make sure all our classes have o2 namespace

### ISSUE THREAD

**Issue by sawenzel** [AliceO2Group/AliceO2#327]

**Comment by sawenzel** [comment]
attaching a list of classes without outer namespace:

[classes_without_namespace.txt](https://github.com/AliceO2Group/AliceO2/files/909494/classes_without_namespace.txt)

**Comment by sawenzel** [comment]
@matthiasrichter , @Barthelemy : Can you please take a look what concerns the aliHLT + QC classes?

**Comment by Barthelemy** [comment]
sure
I will add the namespace
is it just o2 ? or o2::qc ?

**Comment by sawenzel** [comment]
@Barthelemy : I am not sure about our "inner" namespace policy which probably needs some discussion. But "o2::qc" should be ok.

**Comment by Barthelemy** [comment]
@sawenzel done
