### ISSUE TITLE
AliceO2, libCDDB.so error

### ISSUE THREAD

**Issue by frmanso** [AliceO2Group/AliceO2#338]
Hello,

    I have installed FairSoft, DDS and then FairRoot with success on a SL6 machine. When I try to install and make AliceO2, I obtained the following message:  any hint? thanks, F. Manso.

[  9%] Linking CXX shared library ../lib/libCCDB.so
CMakeFiles/CCDB.dir/src/ConditionsMQClient.cxx.o: In function `boost::this_thread::sleep(boost::posix_time::ptime const&)':
/users_local1/manso/O2/external/include/boost/thread/pthread/thread_data.hpp:278: undefined reference to `boost::this_thread::hidden::sleep_until(timespec const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libCCDB.so] Error 1
make[1]: *** [CCDB/CMakeFiles/CCDB.dir/all] Error 2
make: *** [all] Error 2

I have proceed to the installation of AliceO2 as following:

> git clone ­-b dev https://github.com/AliceO2Group/AliceO2.git
> cd AliceO2
> mkdir build_o2
> cd build_o2
> export SIMPATH=/users_local1/manso/O2/external
> export FAIRROOTPATH=/users_local1/manso/O2/external/FairRoot
> /users_local1/manso/O2/external/bin/cmake -DFAIRROOT_INCLUDE_DIR=$FAIRROOTPATH/include -DFAIRROOT_LIBRARY_DIR=$FAIRROOTPATH/lib -DCMAKE_CXX_FLAGS=-std=c++11 -DDOC_INSTALL=ON  -DBOOST_ROOT=/users_local1/manso/O2/external -DVc_DIR=/users_local1/manso/alice/sw/slc6_x86-64/Vc/1.2.0_ROOT6-1/lib/cmake/Vc ..
> make

**Comment by bovulpes** [comment]
Hello,
I have pulled the today's FairRoot/dev and AliceO2/dev and indeed the build of the latter is broken.

Bogdan.

**Comment by bovulpes** [comment]
I guess it comes from this commit on FairRoot:

https://github.com/FairRootGroup/FairRoot/commit/7ab1fd27d5699f3c4e1c2219b55d4eee467e8424

**Comment by kouzinopoulos** [comment]
I am rebuilding my copy of O2 now. In the mean time, can you check if adding Boost::date_time at line 250 of the cmake/O2Dependencies.cmake file (under Boost::filesystem) solves the issue?

**Comment by bovulpes** [comment]
@kouzinopoulos: actually I have another error, see attached file.
I have also added the Boost::date_time 

[make.log.txt](https://github.com/AliceO2Group/AliceO2/files/935183/make.log.txt)

**Comment by dennisklein** [comment]
@bovulpes @frmanso Which `cmake` and `boost` versions are you using?

**Comment by rbx** [comment]
@bovulpes looking at the log file, it seems like some part of your code still sees some old build material. The Terminate/Shutdown methods of FairMQDevice (or its children) don't exist neither in FairRoot nor in AliceO2 dev branches.
Could you just try to wipe your build directory?

**Comment by matthiasrichter** [comment]
I had the same problem recently. It comes from the fact that some of the old `FairMQDevice` methods have been removed. In my case it turned out that the old header files have still been installed. The AliceO2 build takes the header files from the FairRoot installation. This results in a mismatch, because the `FairMQDevice` class as defined in the old header has some methods which are not implemented in the newer library.

I have solved it by removing the complete include directory of the FairRoot installation and running the installation again.

Maybe this is a glitch of https://github.com/alisw/alibuild in the handling of development copies

**Comment by bovulpes** [comment]
I did as Mathias proposed, remove all includes from FairRoot and install it again and the errors are gone.
And just for the record, I did not install my soft using alibuild, I did it one by one separately.

**Comment by frmanso** [comment]
Ok thanks for the help, I will try this fix asap (Cern trip until friday).

**Comment by matthiasrichter** [comment]
Indeed, thinking more about it it's unlikely to be related to `alibuild`, seems to be something in the FairRoot cmake setup which does not install the updated headers. I will try to reproduce the case.

**Comment by dennisklein** [comment]
@frmanso If you cannot fix your linker error with the above suggestions, could you please provide some more debug infos:
* Run `make clean && make VERBOSE=1 CCDB` in your `AliceO2/build_o2` directory and attach the output here
* Run `git show -s` in your FairSoft, FairRoot and AliceO2 source directories, you have built and installed from, and post the output here.

**Comment by sawenzel** [comment]
Is this issue still relevant or can it be closed?

**Comment by bovulpes** [comment]
For me it is not relevant any more, I don't know about @frmanso but I guess it can be closed since things have for sure evolved since.

**Comment by frmanso** [comment]
Hello,  It's fine for me. We can close it.Best regards. Franck.  


Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : Bogdan Vulpescu <notifications@github.com> Date : 02/08/2017  09:06  (GMT+01:00) À : AliceO2Group/AliceO2 <AliceO2@noreply.github.com> Cc : frmanso <manso@clermont.in2p3.fr>, Mention <mention@noreply.github.com> Objet : Re: [AliceO2Group/AliceO2] AliceO2, libCDDB.so error (#338) 
For me it is not relevant any more, I don't know about @frmanso but I guess it can be closed since things have for sure evolved since.
