### ISSUE TITLE
Build fails if ZeroMQ is not found

### ISSUE THREAD

**Issue by matthiasrichter** [AliceO2Group/AliceO2#344]
cmake configuration fails if ZeroMQ is not found because `ZeroMQ_INCLUDE_DIR` is used but not set. This is triggered by a failure of FindZeroMQ from FairRoot, a valid ZeroMQ version from the system directories is not found.

In principle there should be no dependency on ZeroMQ directly in the code, everything goes via FairMQ. However, `ZeroMQ_INCLUDE_DIR` is used in many module buckets. The only indirect dependency is in  `DataFormats/TimeFrame/test/TimeFrameTest.cxx`. Here the include of `FairMQTransportFactoryZMQ.h` inderictly requires include of `zmq.h`.

TODO

- [x] clean buckets, remove `ZeroMQ_INCLUDE_DIR`
- [x] conditional compilation of `DataFormats/TimeFrame/test/TimeFrameTest.cxx`
- [x] check why FairRoot `FindCMake` does not find a valid ZeroMQ installation in the system directories

**Comment by dennisklein** [comment]
Your last point was adressed recently by FairRootGroup/FairRoot#510. Because the history in `dev` was rewritten, you find the relevant commit in FairRootGroup/FairRoot@79c6122ef012bc5 now..

**Comment by matthiasrichter** [comment]
I saw this commit when I checked the history of the file. The build has this commit, but it's still not working. I have to check in more detail.

**Comment by matthiasrichter** [comment]
The cleanup can be done if this PR in FairRoot is merged
https://github.com/FairRootGroup/FairRoot/pull/546

**Comment by matthiasrichter** [comment]
The TODO list is partly fulfilled in #353 

I still need to check the last point what's actually going wrong in the `FindZeroMQ` macro

**Comment by matthiasrichter** [comment]
I can confirm that FairRoot in the current  dev branch is correctly picking up a valid ZeroMQ installation from the system.  See also https://github.com/FairRootGroup/FairRoot/issues/512
Closing this issue.
