### ISSUE TITLE
Review of TrackID field in hit classes

### ISSUE THREAD

**Issue by sawenzel** [AliceO2Group/AliceO2#355]
@MohammadAlTurany, @wiechula

Do we still need the trackID member in hit classes ... given the fact the FairLink MC truth will have this information anyway?

**Comment by shahor02** [comment]
@sawenzel , I would keep it until we substitute all queries pf hit->GetTrackID by the query from the link

**Comment by sawenzel** [comment]
Sure. I did not intend to remove it now. Just wanted to understand if there is an independent need for it.

**Comment by shahor02** [comment]
It would be tempting to get rid of MC labels in all classes, but should not try 1st to asses the CPU overhead of accessing trackID via FairLink?

**Comment by wiechula** [comment]
I agree with Ruben

**Comment by sawenzel** [comment]
Closing this. We keep the trackID and do not use the FairLink ptr.
