### ISSUE TITLE
Consider making TPC::BetheBloch process with floats

### ISSUE THREAD

**Issue by sawenzel** [AliceO2Group/AliceO2#356]
The BetheBlochAleph function exists only with double signature but is called in a purely float context. Can we change the signature to take floats? This would enhance the speed of the hits treatment in the TPC.

**Comment by sawenzel** [comment]
@wiechula: Any comment

**Comment by wiechula** [comment]
This should be fine. I don't think we need double precision here. But one could also consider making it a template function.

**Comment by sawenzel** [comment]
Agreed.

**Comment by sawenzel** [comment]
Available as template function in dev.
