### ISSUE TITLE
FairMQDevice does not have function MakeTransport

### ISSUE THREAD

**Issue by bovulpes** [AliceO2Group/AliceO2#360]
Hello,

The commit 5f2610c2 introduces

FairMQDevice::MakeTransport("zeromq")

but I get an error at compilation, since FairMQDevice does not have this function.

regards,

Bogdan.

**Comment by matthiasrichter** [comment]
Hi Bogdan, please also update the FairRoot installation. This function has been introduced recently in FairRoot dev, just before the commit you mention.

Cheers
Matthias

**Comment by bovulpes** [comment]
Hi Matthias,

You're right, I was checking by mistake the "master" branch of FairRoot and did not find this.

cheers,

Bogdan.
