### ISSUE TITLE
Run CI for pull requests also on Mac OS 

### ISSUE THREAD

**Issue by matthiasrichter** [AliceO2Group/AliceO2#361]
A Mac OS system needs to be added to the CI in order to detect PR errors on Mac

**Comment by matthiasrichter** [comment]
@dberzano is this something you could work on?

**Comment by dberzano** [comment]
Indeed. Currently, our technical limitation is that we need to do everything on CC7, but I am trying to figure out how to extend it. Won't be immediate though.

**Comment by matthiasrichter** [comment]
@ktf @sawenzel @dberzano probably this issue is in the wrong project, can one of you move it to a more appropriate one? I think we should add some priority here.

**Comment by dberzano** [comment]
You are right, see [OCCF-42](https://alice.its.cern.ch/jira/browse/OCCF-42).

**Comment by matthiasrichter** [comment]
Thanks a lot, Dario!
