### ISSUE TITLE
Unaccounted extra padding in DataHeader

### ISSUE THREAD

**Issue by ktf** [AliceO2Group/AliceO2#373]
Looks like we have some unaccounted extra padding in DataHeader. The following fails:

```C++
DataHeader test;
assert(((char*)(&test.dataOrigin) - (char *)(&test.reserved)) == -4);
```

How about we move away from C++ to define in memory data structures and we use some padding aware IDL, generating then the C++ from it. I think this would result in a much cleaner implementation at the cost of some trivial code generation.

**Comment by ktf** [comment]
By the way: `((char*)(&test.dataOrigin) - (char *)(&test.reserved))` returns -8 in my case...

**Comment by matthiasrichter** [comment]
Interesting, that probably means that the definition of the templated `Descriptor`in DataHeader:216 is not working as intendet.
```bash
template <int N, typename PrinterPolicy = Internal::defaultPrinter>
struct Descriptor {
...
```

`DataOrigin` is defined as 
```bash
constexpr uint32_t gSizeDataOriginString = 4;

typedef Descriptor<gSizeDataOriginString, printDataOrigin> DataOrigin;
```

@ktf please assign to me

**Comment by matthiasrichter** [comment]
@ktf do you have a concrete IDL in mind?

**Comment by ktf** [comment]
ASN.1 is the only one I found which allows you to express endianness and unserialised data structures, at least as far as I can tell, not sure how viable it is. Thrift might also be tweaked to work that way, I think, since it separated description and actual serialisation. All the others I know of (flatbuffers, protobuf) have some sort of serialisation happening, this would mean that we lose part of the "print the structure and see what it is" feature. Maybe flat buffer is close enough though.

**Comment by matthiasrichter** [comment]
I have extended to unit test for `DataHeader.h` (still lacks many tests)
```bash
$> bin/dataHeaderTest 
Running 3 test cases...
size of BaseHeader: 32
size of DataHeader: 88
dataDescription:             size 16 at 32
dataOrigin:                  size  8 at 48
reserved:                    size  4 at 56
payloadSerializationMethod:  size  8 at 64
subSpecification:            size  8 at 72
payloadSize                  size  8 at 80
```
The `DataOrigin` member should be of size 4. Investigating ...

**Comment by matthiasrichter** [comment]
I have located it, stupid mistake: the `Descriptor` struct defines an additional member , nicely hidden between all the lines.
```bash
  PrinterPolicy printer;
```
I'm correcting this and I will extend the unit test.

**Comment by ktf** [comment]
However that does not explain how come Mikolaj got 80 bytes yesterday. By
the way, how do we plan to deal with this kind of issues in the future?
What do we do if we realise that by accident something unintended crippled
in?

**Comment by mkrzewic** [comment]
Hi the 80 I get from an independent implementation in aliroot (and used to get 80 as well in O2 with gcc 4.9). The implementation in aliroot is simple, just a struct with uint32_t and uint64_t fields, no unions.

**Comment by matthiasrichter** [comment]
no, we have to follow up why Mikolaj got 80. Another interesting observation: The structure size was always double the size of the number given to the template. I do not have a good explanation for that.

Anyway, this restores my trust into compilers.

For the moment I think it's fine to correct the bug and add better tests. But let's keep the topic in mind, and probably do some dedicated brainstorming.

**Comment by matthiasrichter** [comment]
good, everything understood now.
