### ISSUE TITLE
TestTPCDigitContainer fails + Review of other TPC unit tests

### ISSUE THREAD

**Issue by sawenzel** [AliceO2Group/AliceO2#386]
One of our unit test fails (even in pull requests completely unrelated to this). This should be investigated and the test re-enabled.

**Comment by ktf** [comment]
Disabling the test in #387.

**Comment by sawenzel** [comment]
Please review all the other TPC tests at the same time.

**Comment by sawenzel** [comment]
@a-mathis : Any news on this?

**Comment by a-mathis** [comment]
The errors are related to a) the change to a new Vc version and b) to the introduction of FairLinks.
As this issue is not urgend, a fix will be provided with the next pull request from TPC.

**Comment by a-mathis** [comment]
Fixed in https://github.com/AliceO2Group/AliceO2/pull/505
