### ISSUE TITLE
Revision of test.C macro for DataHeaders

### ISSUE THREAD

**Issue by sawenzel** [AliceO2Group/AliceO2#395]
The `test.C` for DataHeaders seems outdated. For example there is no `ROOTobjectHeader` class anymore.

I suggest to revise this file and possibly to delete it. I believe we should put tests into executables and not macros in order to be sure that they are compiled and run each time.

**Comment by sawenzel** [comment]
@mkrzewic , @matthiasrichter : Could one of you please take a look here?

**Comment by mkrzewic** [comment]
PR #397 takes care of this
