### ISSUE TITLE
testMessageFormat out of bounds error

### ISSUE THREAD

**Issue by ironMann** [AliceO2Group/AliceO2#402]
Hi, I've seen an occasional failure of testMessageFormat test. Here's a diff to illustrate the problem:

```diff
--- a/Utilities/aliceHLTwrapper/test/testMessageFormat.cxx
+++ b/Utilities/aliceHLTwrapper/test/testMessageFormat.cxx
@@ -133,7 +133,7 @@ namespace o2::AliceHLT {
         o2::Header::hexDump("Payload block", output.mP, output.mSize);
-        o2::Header::hexDump("  Data string", dataFields[dataidx].c_str(), dataFields[dataidx].size());
+        o2::Header::hexDump("  Data string", dataFields[dataidx%2].c_str(), dataFields[dataidx%2].size());
         const char* data = (char*)output.mP;
```
Not sure if that is the proper fix though. ping @matthiasrichter 

Additionally,
I would suggest using GCC Undefined Behavior Sanitizer (ubsan) to run series of CI unit tests. It can catch a lot of small issues that otherwise slip under the radar.

**Comment by matthiasrichter** [comment]
Thanks @ironMann for spotting this. Correct fix in the PR. About the other suggestion that is probably something to the build system. @ktf, which would be the correct project to make a feature request to? alibuild or alibot?

**Comment by ktf** [comment]
I would use https://github.com/alisw/ali-bot. I agree Address Sanitizer and Undefined Behavior Sanitizer are probably a good idea...
