### ISSUE TITLE
constexpr constructor does not have empty body

### ISSUE THREAD

**Issue by bovulpes** [AliceO2Group/AliceO2#408]
Hello,

I have a compilation error here:  

/// constructor from a compile-time string
constexpr Descriptor(const char* in) : str{0}
  {
    int i = 0;
    for (; in[i] && i < N ; ++i) {
      str[i] = in[i];
    }
  }

I am using g++ (GCC) 4.9.4

Thanks.

cheers,

Bogdan.

**Comment by ktf** [comment]
This is only valid if you have a C++14 capable compiler (or at least one which allows extended constexpr). [Apparently](https://gcc.gnu.org/projects/cxx-status.html) you need at least GCC 5 for this. @dberzano @mkrzewic might have more details about this.

**Comment by sawenzel** [comment]
Do you build using alibuild? In principle, the O2 recipes now demand gcc 6.2 (which is a recent change). alibuild should automatically provide gcc 6.2 for you.
