### ISSUE TITLE
Correct copyright information

### ISSUE THREAD

**Issue by matthiasrichter** [AliceO2Group/AliceO2#410]
After #405 the copyright notice in the files is in limbo state. Also other pointers are either wrong or incomplete. Here is a list of actions to be taken

- [ ] remove conflicting old license notices
- [x] add the full license information to https//alice-o2.web.cern.ch/ and cite the correct link in the license notice (http instead of https)
- [ ] formal agreement of developers by approving PR or citation of the meeting/minutes with the corresponding decision
- [x] add file `COPYING` which is referenced in the copyright notice
- [x] adjust `alidist` copyright check

**Comment by matthiasrichter** [comment]
first related PR is #513

**Comment by dberzano** [comment]
#513 has been merged.

**Comment by sawenzel** [comment]
Is this issue still relevant or can it be closed? If not what is the status?

**Comment by matthiasrichter** [comment]
we did not solve all the items, but it doesn't seem to be very important, closing the issue
