### ISSUE TITLE
Missing package sip-check in Mac OS Sierra

### ISSUE THREAD

**Issue by urasantonio** [AliceO2Group/AliceO2#419]
Dear experts, 

I've tried to install ALICE O2 with aliBuild (aliBuild init O2@dev), and AliDoctor finds that some packages are missing:

----------------------------------------------------------------

aliDoctor O2
...

==> The following packages will be picked up from the system:
    
    - FreeType
    - CMake
    - Python
    - libxml2
    - zlib
    - libpng
    - autotools
    - boost
    
    If this is not you want, you have to uninstall / unload them.

==> The following packages will be build by aliBuild because they couldn't be picked up from the system:
    
    - Python-modules
    - protobuf
    - SWIG
    - yaml-cpp
    - nanomsg
    - ZeroMQ
    - GSL
    
    This is not a real issue, but it might take longer the first time you invoke aliBuild.

==> The following packages are system dependencies and could not be found:
    
    - sip-check

----------------------------------------------------------------

Is anyone aware of how this issue could be fixed? Apparently, brew dies not know the sip-check package...

Cheers,
Antonio

**Comment by ktf** [comment]
Dear Antonio,

sip-check is not really a package, but the fact that in order for aliroot to fully function on mac, you need to disable the system integrity protection.

See also:

https://dberzano.github.io/alice/install-aliroot/prereq-osx/#system_integrity_protection

We should indeed have a better message for that.

-- 
Ciao,
Giulio

**Comment by ktf** [comment]
Closing this. Feel free to reopen if you have more troubles.

**Comment by urasantonio** [comment]
Thanks Giulio, the procedure described in Dario's page fixed the problem for me. 

Ciao
Antonio
