### ISSUE TITLE
Error in building O2 (ERROR:root:Error parsing)

### ISSUE THREAD

**Issue by urasantonio** [AliceO2Group/AliceO2#421]
Dear experts, 

when building ALICE O2 with "aliBuild --debug --defaults o2 build O2" I find the error reported in the attached log. Any hint?

Thanks, cheers
Antonio
[log.txt](https://github.com/AliceO2Group/AliceO2/files/1088615/log.txt)

**Comment by sawenzel** [comment]
I would try to install the followong python modules on your system:

- matplotlib
 - numpy
 - certifi
 - ipython
 - ipywidgets
 - ipykernel
 - notebook
 - metakernel
 - pyyaml

You do this by saying:

`sudo pip install numpy` etc.

In general try to say `aliDoctor O2 --default o2` which will tell you the packages that alibuild tries to take from the system. Try to maximise this set of packages.

**Comment by urasantonio** [comment]
Thanks Sandro, I managed to install some of the suggested packages and the error disappared. The building is now crashing in another point, I'll open a new issue for that.

Cheers
Antonio
