### ISSUE TITLE
Error in building LHAPDF

### ISSUE THREAD

**Issue by urasantonio** [AliceO2Group/AliceO2#423]
Dear experts, 

A new error when building ALICE O2 with "aliBuild --debug --defaults o2 build O2", see the attached log. This time is about LHAPDF...
[log.txt](https://github.com/AliceO2Group/AliceO2/files/1089661/log.txt)

Thanks, cheers
Antonio

**Comment by urasantonio** [comment]
Dear experts, any hint about this issue?

Thanks, cheers
Antonio

**Comment by ktf** [comment]
@qgp can you please have a look at this? Looks like the LHAPDF installation is lacking one of the data files.

**Comment by ktf** [comment]
@urasantonio which commit of alidist are you using?

**Comment by qgp** [comment]
Hi,

it seems that lhapdf finds these pdf sets already somewhere and doesn't install them. The check in the recipe then looks explicitly in the build dir and doesn't find the requested PDFs.

@urasantonio: Are you sure you run your build without any environment of another installation loaded, in particular  LHAPATH? Can you provide the environment variables in the shell where you try the build?

Cheers,
   Jochen

**Comment by ktf** [comment]
@qgp maybe we should have `LHAPATH` explicitly unset at the beginning of the recipe?

**Comment by qgp** [comment]
@ktf could be done, but similar problems could occur for other env variables, couldn't they? So, if we want to be safe against this, we should unset essentially everything. Maybe the saner thing would be to issue a warning if any module files are loaded when the build is started?

**Comment by ktf** [comment]
Not so easy, I am afraid, since we do want to support system tools and they might require those variables to be set. I think it's much better to protect single recipes against pollution of known unwanted env (other obvious examples are the various FairSoft env or ROOTSYS). I will try to add it to the best practices for recipes.

**Comment by qgp** [comment]
@ktf that's why I suggested a warning when module files are loaded.

Just unsetting variables is also not so easy, what if a variable gets overridden intentionally?

**Comment by ktf** [comment]
If it's overridden intentionally it should be handled explicitly in any case. I.e. there should be something like:

```bash
if [ $LHAPDF ]; then
  echo "I am using the user provided LHAPDF"
  ..copy / link the datafile from the user provided sources.
else
  ..do something else to get our own LHAPDF datafiles
fi
```

**Comment by qgp** [comment]
Well, that's my point, simply adding to the best practices for the recipes to unset variables doesn't seem optimal to me. The instructions would have to be a bit more involved. What you propose now is essentially the warning that it's using something else, only now based on the env variable instead of a module file. Anyway, we are hijacking a bit this issue ;-)

**Comment by urasantonio** [comment]
Hi, thanks for the replies, I only see them now! 

- I'm not sure how I can retrieve the alidist commit I'm using: is there any specific command to find it?

- Concerning the LHAPATH variable, it is not set at all: neither at the beginning of the build, nor when the building stops with the error under discussion. I explicitly checked I have no variable set with name starting with LH.

**Comment by urasantonio** [comment]
Dear experts, just to tell you that after restarting from scratch the whole O2 installation, the problem with LHAPDF persists (see new, attached log). Any hint?
[log.txt](https://github.com/AliceO2Group/AliceO2/files/1157687/log.txt)

**Comment by aphecetche** [comment]
Hi Antonio,

Not that it's of tremendous help to you, but I've just tried an installation from scratch (and with no prior environment set) :

```
cd ~tmp2
rm -rf *
aliBuild --debug --defaults o2 build lhapdf
```

and everything went fine...

```
❯ uname -a
Darwin nanpc420.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
❯ clang --version
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by urasantonio** [comment]
Hi Laurent, thanks for the feedback: on which OS did you build it?

**Comment by ktf** [comment]
@urasantonio and myself sat together and I think https://github.com/alisw/alidist/pull/800 should fix the problem. @qgp can you validate it?

**Comment by ktf** [comment]
Let's close this and move the discussion to the PR.
