### ISSUE TITLE
non-conforming copyright notice in DataCompression files

### ISSUE THREAD

**Issue by sawenzel** [AliceO2Group/AliceO2#427]
A few files slipped through the code checker at #422:

DEBUG:O2:0: ..sw/SOURCES/O2/dev/0//./Utilities/DataCompression/include/DataCompression/DataDeflater.h:1:1: error: missing or malformed copyright notice
DEBUG:O2:0: ../sw/SOURCES/O2/dev/0//./Utilities/DataCompression/include/DataCompression/TruncatedPrecisionConverter.h:1:1: error: missing or malformed copyright notice

@matthiasrichter: Can you please correct this?

**Comment by matthiasrichter** [comment]
@sawenzel  this has been fixed in dfb7818a63cf56d0f12bbbd198d4fa2212ecd8fb and can be closed now
