### ISSUE TITLE
Error in building O2 since #422

### ISSUE THREAD

**Issue by dr4kan** [AliceO2Group/AliceO2#428]
Hi, 

I am getting some errors when compiling O2 since PR #422. 

Thanks for checking.

`/alice/sw/SOURCES/O2/dev/0/Utilities/DataCompression/test/../include/DataCompression/DataDeflater.h:47:48: warning: static_assert with no message is a C++1z extension [-Wc++1z-extensions]
  static_assert(Length <= 8 * sizeof(code_type));
                                               ^
                                               , ""
/alice/sw/SOURCES/O2/dev/0/Utilities/DataCompression/test/test_DataDeflater.cxx:99:23: error: implicit instantiation of undefined template 'std::__1::array<char, 8>'
  std::array<char, 8> data = {'d','e','a','d','b','e','e','f'};
                      ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__tuple:116:65: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TYPE_VIS_ONLY array;
                                                                ^
/alice/sw/SOURCES/O2/dev/0/Utilities/DataCompression/test/test_DataDeflater.cxx:124:23: error: implicit instantiation of undefined template 'std::__1::array<char, 8>'
  std::array<char, 8> data = {'d','e','a','d','b','e','e','f'};
                      ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__tuple:116:65: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TYPE_VIS_ONLY array;
                                                                ^
/alice/sw/SOURCES/O2/dev/0/Utilities/DataCompression/test/test_DataDeflater.cxx:169:23: error: implicit instantiation of undefined template 'std::__1::array<char, 8>'
  std::array<char, 8> data = {'d','e','a','d','b','e','e','f'};
                      ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__tuple:116:65: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TYPE_VIS_ONLY array;
                                                                ^
1 warning and 3 errors generated.`

**Comment by sawenzel** [comment]
@dr4kan: What is your compiler version?

**Comment by dr4kan** [comment]
@sawenzel: 

Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by sawenzel** [comment]
@dr4kan : I confirm this error. @matthiasrichter : We should try to be able to compile with MacOS El Capitan as long as possible. Would it be possible to use the older static_assert API including an error string?

Generally, I believe we should seriously reconsider to have a MacOS based pull request check to avoid such things in the future.

**Comment by matthiasrichter** [comment]
Hi folks,sorry for this,think I have hit this already before. I will fix this later today,of course compilation on Macos must not be broken.

@dberzano @sawenzel @ktf can we run CI on a mac system? #361

**Comment by matthiasrichter** [comment]
Reading the error message more carefully pointed me to the `std::array` to be the problem and very likely its simply a missing include. I also fixed the `static_assert` to take also an error string.

@dr4kan could you please check and approve PR #432  in case the problem is solved, thanks.

**Comment by dberzano** [comment]
@matthiasrichter I have opened [OCCF-42](https://alice.its.cern.ch/jira/browse/OCCF-42) to track the issue of running a build with Clang.

**Comment by dr4kan** [comment]
@matthiasrichter PR #432 does not compile either even though the error is elsewhere now

Utilities/aliceHLTwrapper/src/Component.cxx:169:13: error: use of undeclared identifier 'ENOKEY'
    return -ENOKEY;

**Comment by sawenzel** [comment]
@matthiasrichter : Can you please investigate the ENOKEY problem or find an alternative solution.

**Comment by sawenzel** [comment]
@dr4kan : You should be able to compile now (I provided a temporary fix on the ENOKEY problem). But we will keep this issue open until properly corrected.

**Comment by matthiasrichter** [comment]
Thanks @sawenzel,probably cerrno on mac does not define this error code.Maybe I will drop all the error codes and use exceptions later.
