### ISSUE TITLE
Confused about namespace naming convention

### ISSUE THREAD

**Issue by aphecetche** [AliceO2Group/AliceO2#441]
(reposting here a Slack question that might have been lost between github notifications in the #aliceo2 channel...)

Dear all, I’m a bit confused by the naming convention for namespaces. According to  http://htmlpreview.github.io/?https://github.com/AliceO2Group/CodingGuidelines/blob/master/naming_formatting.html it should be lowercase with underscores, but in the current O2 repo I see some upper cases (e.g. for detectors), some camelCase, and some that seem to respect the convention...

What is the situation really ?

Thanks

**Comment by Barthelemy** [comment]
Hi Laurent, 
I do not remember if there was a special reasoning for the convention about naming the namespaces. It is not yet enforced/checked in the repo (@sawenzel can you confirm ? ), thus the little mess. 
I would advise to follow the convention. 
Cheers,

**Comment by sawenzel** [comment]
On new code we should apply what is written in the document. I started working on the code checker part for this so at some moment all namespaces will have to follow the rule.

**Comment by ihrivnac** [comment]
Hi,
The rule in the original document, agreed by O2 project, was:
" Namespace names follow camel case convention and start with an upper case letter: <code>MyNamespace</code>."
The change of the rule is indeed inconsistent with General naming rules, where we require camel case convention and also with the examples given in the section Namespaces in the coding guidelines section. 
Cheers,

**Comment by ktf** [comment]
The original rule was amended in:

https://github.com/AliceO2Group/CodingGuidelines/commit/66022f9b214176a3daa0c1a7b80cdeacc7a61a1f

after discussion in CWG11 (now WP3). As written in the ticket, the rationale is that camel cased namespaces can be confused with class names. As @sawenzel pointed out, all new code should have lowercase_underscore namespaces and we should get to convert the old code to comply as soon as possible.

**Comment by Barthelemy** [comment]
ok, at least I understand why I was confused.

**Comment by ihrivnac** [comment]
Ok, thanks. This should be also mentioned in General Naming Rule, as an exception to the camel case convention used everywhere else.
When making the changes in the code, do you plan to change the case also for the detector names in namespaces? And what about the directories names, will they follow the changes, too?

**Comment by ktf** [comment]
I would propose we change detector names to lower case (to be discussed, I guess). However the directory naming has no connection to the namespaces (e.g. `DataFormats/Headers/include/Headers/DataHeader.h` has `o2::Header` in it) so that will for sure remain unchanged.

**Comment by aphecetche** [comment]
I buy the argument that lower case namespaces help to visually distinguish namespaces from class names, so I'd indeed be in favour of applying the rule consistently, hence including detector names.

**Comment by sawenzel** [comment]
Closing this. The situation has been clarified. A tool to check the namespace rule is currently being implemented.
