### ISSUE TITLE
(Unit) Test framework

### ISSUE THREAD

**Issue by aphecetche** [AliceO2Group/AliceO2#442]
Trying to get myself into the "TDD" habit, I'd have a couple of questions : 

- has O2 made a definite choice on the test framework (Boost or Google, e.g. why did FairRoot switched to Google recently ?)

- if the framework is Boost, any O2-specific introductory material on how to use it (e.g. which usage variant : include only, dynamic lib, etc... ) or should one "just read the existed committed code" (which is always a dangerous proposition IMO ;-) )

Thanks,

**Comment by Barthelemy** [comment]
At the moment the choice is boost.test. There have been some discussions about it recently. There are no guides unfortunately.

**Comment by sawenzel** [comment]
There are a few usages of boost.test in O2 and I believe it is easy to understand. And the O2_MAKE_TEST() macro is easy to use to setup a test in the cmake. You can take a look here AliceO2/DataFormats/simulation/ for inspiration.

**Comment by aphecetche** [comment]
OK, I'll use boost.test for the time being. 

Still, for my own education, maybe @MohammadAlTurany can comment on why FairRoot switched to Google Test ?

Thanks

**Comment by sawenzel** [comment]
Closing as this is not a real issue (problem to fix or task to achieve).
