### ISSUE TITLE
Change to ROOT v6-09-04 or higher

### ISSUE THREAD

**Issue by shahor02** [AliceO2Group/AliceO2#453]
Hello @dberzano @ktf 

to develop the geometry (hits/clusters) transformations related packages we need templated version of ROOT::Math::Impl::Transform3D< T > class available starting from v6-09-04. Is there something against to switching to this version?

Cheers,
 Ruben

**Comment by dberzano** [comment]
As you can see in alisw/alidist#777 we mean to switch to an even more recent version, but we were holding on due to a compilation trouble concerning ROOT itself.

**Comment by shahor02** [comment]
Thanks @dberzano ! From the PR it was not clear if the problems still persist. Will it be merged soon?

**Comment by dberzano** [comment]
I am testing the compilation now. That PR needs to be changed in any case, as that specific ROOT hash has compilation problems. Stay tuned...

**Comment by dberzano** [comment]
OK I have managed to work around the problem (which is a CMake one) but it requires an update in the ROOT recipe. Will update soon, keep an eye on alisw/alidist#777.

**Comment by dberzano** [comment]
Can you check with the latest `alidist` from master, and close the ticket if it works?

**Comment by shahor02** [comment]
Thanks @dberzano , worked w/o any problem!

**Comment by Barthelemy** [comment]
It seems that I have a new warning when launching some apps since the new ROOT : 
```Warning in <TInterpreter::ReadRootmapFile>: class  ROOT::Math::Cartesian3D<float> found in libGenVector.so  is already in SimulationDataFormat.so 
Warning in <TInterpreter::ReadRootmapFile>: class  ROOT::Math::PositionVector3D<ROOT::Math::Cartesian3D<float>,ROOT::Math::DefaultCoordinateSystemTag> found in libGenVector.so  is already in SimulationDataFormat.so 
```
Do you think it is related ?

**Comment by dberzano** [comment]
I do not, however those warnings are generally innocuous. Unless there's gazillions of them. Is it the case?

**Comment by shahor02** [comment]
@Barthelemy : yes, this template was not instantiated in root v6-08 (so we had do this in our SimulationDataLinkDef.h) but is instantiated in v6-10. We can now suppress the lines
```
#pragma link C++ class ROOT::Math::Cartesian3D<float>+;
#pragma link C++ class ROOT::Math::PositionVector3D<ROOT::Math::Cartesian3D<float>,ROOT::Math::DefaultCoordinateSystemTag>+;
```
in SimulationDataLinkDef.h, but this will create problems for those who are still on v6-08. Since the warning is malign, I would do this only when the code incompatible with v6-08 is pushed.

**Comment by Barthelemy** [comment]
@shahor02 Ok, no problem, let's wait then. 
@dberzano There are only those 2.
