### ISSUE TITLE
Building error after pull (El Capitan)

### ISSUE THREAD

**Issue by dr4kan** [AliceO2Group/AliceO2#487]
Hi,

today I updated my local repo and I found that it no longer compiles on El Capitan.
I also tried starting from scratch with the same result.

Thanks for checking.

`Common/MathUtils/test/testCartesian3D.cxx:17:
/Users/me/alice/sw/SOURCES/O2/dev/0/Common/MathUtils/include/MathUtils/Cartesian3D.h:75:12: error: use of undeclared identifier 'ApplyInverse'
    return ApplyInverse(p);
           ^
/Users/me/alice/sw/SOURCES/O2/dev/0/Common/MathUtils/test/testCartesian3D.cxx:53:18: note: in instantiation of function template specialization 'o2::Base::Transform3D::operator^<float>' requested here
  auto pfti = tr ^ (pft); // operator form
                 ^
In file included from /Users/me/alice/sw/SOURCES/O2/dev/0/Common/MathUtils/test/testCartesian3D.cxx:17:
/Users/me/alice/sw/SOURCES/O2/dev/0/Common/MathUtils/include/MathUtils/Cartesian3D.h:75:12: error: use of undeclared identifier 'ApplyInverse'
    return ApplyInverse(p);
           ^
/Users/me/alice/sw/SOURCES/O2/dev/0/Common/MathUtils/include/MathUtils/Cartesian3D.h:94:11: note: in instantiation of function template specialization 'o2::Base::Transform3D::operator^<double>' requested here
    loc = operator^(mst);
          ^
/Users/me/alice/sw/SOURCES/O2/dev/0/Common/MathUtils/test/testCartesian3D.cxx:55:6: note: in instantiation of function template specialization 'o2::Base::Transform3D::MasterToLocal<double>' requested here
  tr.MasterToLocal(pdt, pdti); // TGeoHMatrix form
     ^
2 errors generated.
`

**Comment by sawenzel** [comment]
We now require ROOTv6.10; It seems that you need to update your alidist and the compilation should then be ok.

**Comment by dr4kan** [comment]
@sawenzel yes you are right. that fixed the error.
thanks.
