### ISSUE TITLE
Cannot do anymore 'alienv load O2/latest' or 'alienv enter O2/latest' on mac

### ISSUE THREAD

**Issue by dr4kan** [AliceO2Group/AliceO2#519]
Hi,

after a rebase I cannot do anymore 'alienv load O2/latest' or 'alienv enter O2/latest' on two different macs. I get the error "ERROR: O2/latest was not found". 
On one of the two mac I also tried a clean install from scratch with the same result. Building was fine.
Never had this issue before. Am I missing something?

Thanks,
Davide.

**Comment by matthiasrichter** [comment]
Hi Davide,
did you check with `alienv q` which packages are available? I'm not sure if `O2/latest` is defined, but `O2::latest` should be defined.

Cheers
Matthias

**Comment by dr4kan** [comment]
O2::latest is not defined in my case...How is it possible?

`$ alienv q | grep O2
VO_ALICE@GEANT3::v2-4_O2-1
VO_ALICE@GEANT3::v2-4_O2-2
VO_ALICE@GEANT4::v4.10.01.p03_O2-1
VO_ALICE@GEANT4_VMC::v3-2-p1-alice1_O2-1
VO_ALICE@GEANT4_VMC::v3-2-p1-alice1_O2-2
VO_ALICE@HepMC::v2.06.09_O2-1
VO_ALICE@ROOT::v6-08-02_O2-1
VO_ALICE@ROOT::v6-10-02_O2-1
VO_ALICE@Vc::1.3.2_O2-1
VO_ALICE@hijing::v1.36_O2-1
VO_ALICE@lhapdf::v6.1.6_O2-1
VO_ALICE@lhapdf::v6.1.6_O2-2
VO_ALICE@pythia::v8223_O2-1
VO_ALICE@pythia::v8223_O2-2
VO_ALICE@pythia6::428-alice1_O2-1
VO_ALICE@vgm::4.3-alice1_O2-1
VO_ALICE@vgm::4.3-alice1_O2-2
`

**Comment by matthiasrichter** [comment]
Difficult to say what happened. In which project have you done the rebase (e.g. O2, alibuild, alidist)? Did you run `alibuild` after that?

I think the cleanest way is to run `alibuild` again after updating also the recipes.

**Comment by ktf** [comment]
which version of alibuild is this?

**Comment by dr4kan** [comment]
@matthiasrichter I have already tried to do a clean installation (I removed the whole alice folder) on one mac, but after building everything I was still unable to load O2.

@kft aliBuild version: 1.4.0rc1

**Comment by dr4kan** [comment]
I did another install from scratch, installing only O2. Now I get "ERROR: AliPhysics/latest was not found". Even "alienv q" leads to the same error. Guys, any ideas? Two different mac computers with two different os versions (el capitan and sierra)...can anybody try to replicata the issue on a mac?

Thanks.

**Comment by matthiasrichter** [comment]
Can you provide some more information, especially the command line you have been using to build. and the complete commands you enter when getting the error messages. That can probably help to trigger more thinking.

To be honest I don't have any idea, just some thoughts. 
- O2 is not depending on AliPhysics, so there is probably no wonder that AliPhysics is not installed when installing only O2
- `alienv` needs the workdir, default is `sw` or `../sw`, meaning this directory needs to be in the folder from where you are running `alienv`. Or you use the `-w` option to set it at command line, or define alienv as a shell function by sourcing `alienv shell-helper`
- do you have anything regarding `alibuild` in your `.bashrc`? Try removing this, start in a clean shell

**Comment by matthiasrichter** [comment]
@dr4kan is this solved now?

**Comment by dr4kan** [comment]
@matthiasrichter a couple of days after I opened this thread, after the n-th git pull for both alisdist and O2, it restarted working again. thanks.
