### ISSUE TITLE
O2 build with tutorial -  protobuf-compiler required

### ISSUE THREAD

**Issue by jmyrcha** [AliceO2Group/AliceO2#550]
ubuntu 17.04
command:
aliDoctor O2 
do not report missing package  `protobuf-compiler` in the system
command:
`aliBuild --defaults o2-daq build O2`
stops on missing /bin/protoc
After installing package  `protobuf-compiler`  there are still not set build environment variable PROTOBUF_ROOT
Setting it 
`export PROTOBUF_ROOT=/usr`
before running aliBuild solved a problem

**Comment by sawenzel** [comment]
Any news on this issue?

**Comment by ktf** [comment]
This should have been fixed by alisw/alidist#896 and associated PRs. Is it not the case?

**Comment by ktf** [comment]
This should be fixed. Closing.
