### ISSUE TITLE
Move ITS Geometry initialization / configuration inside Detector::ConstructGeometry

### ISSUE THREAD

**Issue by sawenzel** [AliceO2Group/AliceO2#559]
Move ITS geometry configuration and initialization inside Detector::ConstructGeometry function.
Goal: easier integration into o2sim and and build_geometry.C macro.

**Comment by sawenzel** [comment]
@mario6829 , @shahor02 , @iouribelikov : As preveously discussed, would it be possible to hide geometry initialization behind the Detector::ConstructGeometry interface so that we can construct the ITS easily inside the `macro/build_geometry.C`?

**Comment by iouribelikov** [comment]
@sawenzel  Sure !  I will try to do it asap.

**Comment by iouribelikov** [comment]
@sawenzel , @mario6829 , @shahor02 : A quick fix is now available here: https://github.com/iouribelikov/AliceO2/tree/dev/
It can be merged, in principal.

**Comment by sawenzel** [comment]
@iouribelikov : Looks good to me. Can you make a pull request?
