### ISSUE TITLE
SimpleStatefulProcessing01 randomly fails with timeout

### ISSUE THREAD

**Issue by sawenzel** [AliceO2Group/AliceO2#597]
One of the unit tests fails sometimes like this:

```
99% tests passed, 1 tests failed out of 112

Total Test time (real) = 1546.91 sec

The following tests FAILED:
	 95 - test_SimpleStatefulProcessing01 (Timeout)
```

**Comment by matthiasrichter** [comment]
Should we fix this unit test or remove it completely (not only from the build?

https://github.com/AliceO2Group/AliceO2/pull/603

**Comment by ktf** [comment]
I think this is fixed. Closing. Please reopen if not the case.
