### ISSUE TITLE
Review SimulationDataFormat/DetectorList.h

### ISSUE THREAD

**Issue by sawenzel** [AliceO2Group/AliceO2#599]
This detectorlist is completely out of date / incomplete. It seems to be used only in the stack + ITS + TPC.
We need to review this class and eventuelly promote other classes to use it or drop it completely.

The question is also how this class relates to novel approaches (such as DetID).

**Comment by sawenzel** [comment]
@shahor02 : Could you take a look here and tell me what you think?

**Comment by sawenzel** [comment]
I think we should automatically couple each Detector class to a DetID so as one can not forget about this in the future.

**Comment by shahor02** [comment]
@sawenzel : I agree, will open PR with modified Detector constructor and use of ID.

**Comment by sawenzel** [comment]
This is fixed with PR #601.
