### ISSUE TITLE
Remove access to FairRootManager from within TPC Digitizer tasks

### ISSUE THREAD

**Issue by sawenzel** [AliceO2Group/AliceO2#609]
With a few towards device processing, FairTask run/exec functions should be completely isolated and should not require access to external services in order to get information

This is currently not the case for a few tasks (such as TPC digitizer);

Deliverable:
a) provide mechanism that pushes required information (such as event number, event time, ...) as input data
  - idea is that the analysis run sets up this information in a separate **in-memory** 
"branch" / channel

b) use this in the digitizers

**Comment by matthiasrichter** [comment]
This very much sounds like the concept what @ktf has in mind for such kind of information in the DPL

**Comment by ktf** [comment]
Yes, indeed. Shouldn't this become "make digitisers conform to`o2::framework::AlgorithmSpec`"? What is missing from the current API to actually get to this point?

**Comment by sawenzel** [comment]
This is no longer relevant as digitization has been moved to DPL.
