### ISSUE TITLE
Integrate MFT into o2sim

### ISSUE THREAD

**Issue by sawenzel** [AliceO2Group/AliceO2#612]
I would like to integrate MFT with o2sim which accumulates all detectors in one single place.

Would it be possible to move configuration of the segmentations inside the Detector construction or somewhere else, so that 
```
if (isActivated("MFT")){
    // mft                                                                                                                                                                                   
    auto mft = new o2::MFT::Detector();
    run->AddModule(mft);
  }
```
is all there needs to be done? 

See also similar issue #559 which was done for ITS.

- [x] integrate MFT into build_geometry.C
- [x] fix / provide segmentation configuration so that o2sim does not crash when MFT used

**Comment by sawenzel** [comment]
At least Detector() should be able to use a standard segmentation and should not crash when none is available.

**Comment by sawenzel** [comment]
@bovulpes: Could you please take a look?

**Comment by bovulpes** [comment]
@sawenzel the MFT code runs fine with the standard segmentation, since we are not using it specifically, but only in the way it is included in the common part with the ITS.
