### ISSUE TITLE
TPC: testHitsDigitsClusters.C macro broken -- needs revision

### ISSUE THREAD

**Issue by sawenzel** [AliceO2Group/AliceO2#637]
This macro is broken and needs some revision:

a) wrong name used for tree
b) needs update to use the correct type for hits (now using deprecated Point but needs sectorwise grouped hits)

**Comment by sawenzel** [comment]
@wiechula : Can you find someone to fix this?

**Comment by wiechula** [comment]
@a-mathis can you please have a look at this? If you don't have time I'll fix it.

**Comment by a-mathis** [comment]
From my point of view we can delete this macro - it was added in the rush before the testbed and in future I would like to have this test automatically done. Apart from that, all this macro does is some visualisation.
