### ISSUE TITLE
Personal file referred in code

### ISSUE THREAD

**Issue by ktf** [AliceO2Group/AliceO2#660]
I see at:

https://github.com/AliceO2Group/AliceO2/blob/dev/Utilities/QC/QCMetricsExtractor/src/MetricsExtractor.cxx#L33

that we have a personal directory mentioned explicitly. Can that be removed and can instructions point on where to find the file?

**Comment by ktf** [comment]
@Barthelemy I am assigning this to you, as I assume you know who this is. Feel free to reassign, please.

**Comment by matthiasrichter** [comment]
@Barthelemy what do you think about this?

**Comment by Barthelemy** [comment]
sorry missed this
will try to look into it today

**Comment by ktf** [comment]
Any news on this?

**Comment by Barthelemy** [comment]
The mergers will be reworked completely by Michal in AGH under the supervision of Jacek. I think that it should reassigned to them. I can't re-assign myself apparently.

**Comment by Barthelemy** [comment]
Michal (@biz1k) can be assigned

**Comment by ktf** [comment]
@biz1k I am adding you as QC Developer. Can you please accept the invitation? Thanks.

**Comment by ktf** [comment]
This still seems to be the case. Can someone please clean it up?
