### ISSUE TITLE
fatal error: 'gsl/gsl' file not found: need to load libSimulationDataFormat.so by hand

### ISSUE THREAD

**Issue by shahor02** [AliceO2Group/AliceO2#668]
Hello,

Compilation of macros involving (indirectly) ``SimulationDataFormat/MCTruthContainer.h`` fails unless the
````libSimulationDataFormat.so```` was loaded by hand beforehand:
``
root [0] .L run_digi.C+
Info in <TUnixSystem::ACLiC>: creating shared library /home/shahoian/tmp/o2sim/./run_digi_C.so
In file included from input_line_11:9:
In file included from ././run_digi.C:19:
In file included from /home/shahoian/alice/sw/ubuntu1604_x86-64/O2/dev-1/include/TPCSimulation/DigitizerTask.h:22:
In file included from /home/shahoian/alice/sw/ubuntu1604_x86-64/O2/dev-1/include/TPCSimulation/Digitizer.h:18:
In file included from /home/shahoian/alice/sw/ubuntu1604_x86-64/O2/dev-1/include/TPCSimulation/DigitContainer.h:19:
In file included from /home/shahoian/alice/sw/ubuntu1604_x86-64/O2/dev-1/include/TPCSimulation/DigitCRU.h:18:
In file included from /home/shahoian/alice/sw/ubuntu1604_x86-64/O2/dev-1/include/TPCSimulation/DigitTime.h:18:
In file included from /home/shahoian/alice/sw/ubuntu1604_x86-64/O2/dev-1/include/TPCSimulation/DigitRow.h:18:
In file included from /home/shahoian/alice/sw/ubuntu1604_x86-64/O2/dev-1/include/TPCSimulation/DigitPad.h:22:
/home/shahoian/alice/sw/ubuntu1604_x86-64/O2/dev-1/include/SimulationDataFormat/MCTruthContainer.h:21:10: fatal error: 'gsl/gsl' file not found
#include <gsl/gsl> // for guideline support library; array_view
``

Why the library is not loaded automatically?

Cheers,
 Ruben

PS macro run_digi.C doing simultaneous digitization of ITS and TPC is attached, but the problem is there with any macro eventually including  ``SimulationDataFormat/MCTruthContainer.h``
[run_digi.C.zip](https://github.com/AliceO2Group/AliceO2/files/1471402/run_digi.C.zip)

**Comment by ktf** [comment]
Is this still an issue?

**Comment by shahor02** [comment]
@ktf: yes, the macro attached above does not compile unless libSimulationDataFormat.so was loaded beforehand, producing 
``
/home/shahoian/alice/sw/ubuntu1604_x86-64/O2/dev-1/include/SimulationDataFormat/MCTruthContainer.h:21:10: fatal error: 'gsl/gsl' file not found
#include <gsl/gsl> // for guideline support library; array_view
``
