### ISSUE TITLE
Potential problem with track parentID when using Geant4

### ISSUE THREAD

**Issue by sawenzel** [AliceO2Group/AliceO2#671]
There seems to be some inconsistency with the parentID of tracks pushed to our (VirtualMC)Stack -- in case of Geant4VMC.

In particular, I see that tracks refer to a primary parentID `n` although this primary particle was already finished (as indicated by the `FinishPrimary`) hook in the VMC application. This is violating the principle that a primary and all its secondaries are transported before a new primary is started.

To reproduce the issue, I created a special branch (https://github.com/sawenzel/AliceO2/tree/swenzel/geant4vmc_parentid_bug) with verbose output in the Stack.

Running `o2sim -n 1 -m TPC -e TGeant4` yields the following output.
This example transports an event of `10` primaries and I notably observe that secondaries for parentId `5` are pushed even after primary `5` and `4` where marked as finished.

```
>>> Event 0
[INFO   ] TPC: Start primary 9
[INFO   ] Pushing track 10 with parent 9
[INFO   ] TPC: Primary finished
[INFO   ] TPC: Start primary 8
[INFO   ] TPC: Primary finished
[INFO   ] TPC: Start primary 7
[INFO   ] Pushing track 11 with parent 7
[INFO   ] TPC: Primary finished
[INFO   ] TPC: Start primary 6
[INFO   ] Pushing track 12 with parent 6
[INFO   ] Pushing track 13 with parent 6
[INFO   ] Pushing track 14 with parent 6
[INFO   ] Pushing track 15 with parent 6
[INFO   ] Pushing track 16 with parent 6
[INFO   ] Pushing track 17 with parent 6
[INFO   ] TPC: Primary finished
[INFO   ] TPC: Start primary 5
[INFO   ] Pushing track 18 with parent 5
[INFO   ] Pushing track 19 with parent 5
[INFO   ] TPC: Primary finished
[INFO   ] TPC: Start primary 4
[INFO   ] Pushing track 20 with parent 4
[INFO   ] Pushing track 21 with parent 4
[INFO   ] TPC: Primary finished
[INFO   ] TPC: Start primary 3
[INFO   ] TPC: Primary finished
[INFO   ] TPC: Start primary 2
[INFO   ] Pushing track 22 with parent 2
[INFO   ] Pushing track 23 with parent 5
[INFO   ] Pushing track 24 with parent 5
[INFO   ] TPC: Primary finished
[INFO   ] TPC: Start primary 1
[INFO   ] TPC: Primary finished
[INFO   ] TPC: Start primary 0
[INFO   ] Pushing track 25 with parent 0
[INFO   ] Pushing track 26 with parent 0
[INFO   ] Pushing track 27 with parent 5
[INFO   ] TPC: Primary finished
```

The same example with Geant3 `o2sim -n 1 -m TPC -e TGeant3` looks completely fine.

**Comment by sawenzel** [comment]
@ihrivnac , @pzhristov , @preghenella, @shahor02 : Any idea would could go wrong here?

**Comment by ihrivnac** [comment]
Could you add in your printing the particles PDG code, so that we can see what are the particles which got postponed till the end?

**Comment by ihrivnac** [comment]
I was wrong when I thought that this behaviour is by default. 
You need to activate "special stacking" to get all secondaries tracked  before the next primary goes in tracking; this is done in g4Config.C:
   Bool_t specialStacking = true;
   Bool_t mtMode = true;
   TG4RunConfiguration* runConfiguration
    = new TG4RunConfiguration("geomRoot", "QGSP_FTFP_BERT", "stepLimiter+specialCuts",
                              specialStacking, mtMode);

**Comment by sawenzel** [comment]
@ihrivnac : This is good news. Thanks a lot!!

**Comment by sawenzel** [comment]
@ihrivnac :  Running with the `specialStacking = true` should probably be the only allowed default as anything else breaks compatibility with the VMC interfaces.

**Comment by sawenzel** [comment]
Closing this as no longer a problem. It should probably still be discussed if `specialStacking = false` can be allowed at all.
