### ISSUE TITLE
Missing/wrong medium in MFT volumes leading to crash with G4

### ISSUE THREAD

**Issue by sawenzel** [AliceO2Group/AliceO2#738]
Running `o2sim -m MFT -e TGeant4` leads to a crash due to undefined medium.

In particular, the following following volumes `MFT_C_i_j_k`, `MetalStack`, `MFTSensor` have either an incorrect medium assigned or this assignment is missing altogether.

**Comment by sawenzel** [comment]
@bovulpes : I tried to debug this to see where these volumes are constructed. But this is rather involved. Could you please take a look yourself or delegate?

**Comment by sawenzel** [comment]
Debugging together with @urasantonio we found the problem:

MFT uses the Alpide chip, which is instantiated using ITS materials. But these materials do not exist when we run just with MFT. So we should decouple the Alpide materials from ITS.

**Comment by bovulpes** [comment]
A known issue, indeed, I never ran it with o2sim but always together with the ITS. I will have a look on it.

**Comment by bovulpes** [comment]
Is duplicating the necessary materials from ITS to MFT acceptable?

**Comment by sawenzel** [comment]
Probably yes but not sure whether it would be good. In the end MFT and ITS want to share the same geometrical volumes, no?

What about making materials/media ALPIDE_xxx which are created independently from ITS, MFT and attached to the ALPIDE chip?

This should now easily be possible by using the singleton class `o2::Base::MaterialManager`.

**Comment by urasantonio** [comment]
I would also be in favor of defining the materials only once, attaching the prefix ALPIDE.

**Comment by bovulpes** [comment]
It is not straightforward, since the functions for creating a mixture, material, medium must be called from an instantiated Detector object: which one, ITS of MFT? or a new one ITSMFT ?

**Comment by urasantonio** [comment]
Yes, what about defining an ALPIDE (more than ITSMFT) "Detector" class?

**Comment by sawenzel** [comment]
So it is not necessary to promote ALPIDE to a detector.

**Comment by iouribelikov** [comment]
@sawenzel Excellent !

**Comment by bovulpes** [comment]
I have prepared an example in bovulpes/mft-alpide-mat with one material created in AlpideChip, please have a look.

**Comment by bovulpes** [comment]
I have a working code in bovulpes/mft-alpide-mat for the MFT only. One needs only to call the AlpideChip::createMaterials function. Also cleaned obsolete materials from the MFT.

**Comment by bovulpes** [comment]
Hi,
Is there any progress in this direction? This time too the ITS must synchronize its code with the MFT. Is my proposal a good common solution?

**Comment by iouribelikov** [comment]
@bovulpes Sorry, Bogdan.  Somehow, I thought that Mario was following this thread, but in fact he is not involved...
@mario6829 Mario, what do you think ?  Is this solution is OK also for you ?
(If yes, let's open a common PR to address this issue)

**Comment by mario6829** [comment]
@iouribelikov @bovulpes I absolutely agree: it's definitely a good solution, I support it.
Cheers
Mario

**Comment by iouribelikov** [comment]
@bovulpes @mario6829 Great !
If it is only a question of adding  AlpideChip::createMaterials(...) to ITS::Detector,
could not you, Mario, indicate to Bogdan where exactly it would be the best to insert it ?

Then, Bogdan would open the corresponding PR, together with this change in the ITS.
  
OK  for everybody ?

**Comment by mario6829** [comment]
@iouribelikov sure: I'll provide @bovulpes all needed information
