### ISSUE TITLE
Problem with medium (mapping) seen in PHOS

### ISSUE THREAD

**Issue by sawenzel** [AliceO2Group/AliceO2#757]
As point out in PR #749, there is an inconsistency with media to volume assignment.

This can be seen by running the commands
```
o2sim -m PHS -n 0
o2sim -m FRAME PHS -n 0
```
yielding the file O2geometry.root;

Analysing this geometry with the following macro  (`root CheckMaterial.C\("PHOS"\)`)

```
void PrintMat(TGeoVolume *v, double& accum) {
  auto mat = v->GetMaterial();
  std::cout << v->GetName() << " " << mat->GetName() << " " << mat->GetDensity() << "\n";
  accum+=mat->GetDensity();
  auto daughtern = v->GetNodes();
  if (!daughtern) return;
  for (int i = 0; i < daughtern->GetEntries(); ++i) {
    auto node = (TGeoNode*)daughtern->At(i);
    auto vol = node->GetVolume();
    PrintMat(vol, accum);
  }
}

void CheckMaterial(const char *vol = "PHOS", const char *file="O2geometry.root")
{
  // Open geometry file
  TGeoManager::Import(file);

  auto mgr = gGeoManager;
  auto entryvol = mgr->FindVolumeFast(vol);

  double checksum = 0.;
  PrintMat(entryvol, checksum);
  std::cout << "Density checksum " << checksum << "\n";
}
```

shows that the material checksum of PHOS is influenced by the presence of FRAME. This is clearly a bug.

**Comment by sawenzel** [comment]
@peressounko : Thanks for spotting this. I will follow this up.

**Comment by peressounko** [comment]
This us caused by use of direct call of TVirtualMC::GetMC()->Medium() in Detectors/Passive/src/FrameStructure.cxx, Detectors/Passive/src/Hall.cxx,Shil.cxx,Pipe.cxx,Dipole.cxx,Absorber.cxx,Magnet.cxx instead of Detector::Medium()

**Comment by sawenzel** [comment]
@peressounko : I think the problem was rather related to the fact that the Cave volume was created in different manner than all the rest of our modules and that its media where not managed by VMC. PR #761 should solve this issue (it does on my local tests).

**Comment by peressounko** [comment]
Same functionality is realized in Detector::Medium() - isn't it? One only should force all systems to use this function instead of direct call VMC::->Medium().

**Comment by sawenzel** [comment]
@peressounko: I expect the bug to be solved. Can you please cross-check (with the current dev branch) before closing this issue?

**Comment by peressounko** [comment]
Yes, issue is solved, thanks.
