### ISSUE TITLE
Switch to new FairRoot tag to avoid double delete on exit from root 

### ISSUE THREAD

**Issue by shahor02** [AliceO2Group/AliceO2#814]
Hi
With new ROOT/v6-12-04 we get double delete on root exit cleanup due to the FairRoot static FairContFact mechanism, sometimes it event hangs. The problem is fixed in the FairRootGroup:dev by https://github.com/FairRootGroup/FairRoot/pull/719, can we have a new tag from it (or use dev directly)?

Cheers,
 Ruben

**Comment by sawenzel** [comment]
I agree. @ktf, @dberzano: Can you please follow this up?

**Comment by sawenzel** [comment]
@shahor02 : Thanks a lot. This indeed solves a long standing issue! Thanks for debugging.

**Comment by sawenzel** [comment]
@dberzano : Thanks for the prompt reaction.
