### ISSUE TITLE
Error in building O2 dev (probably Vc issue)

### ISSUE THREAD

**Issue by bovulpes** [AliceO2Group/AliceO2#843]
Hello,

I am stuck with an error coming from Vc/common/simdize.h (see log) which I can not get rid of. Tried 
to update the recipes but it does not help.
Could you please help?
Thanks.

[log.txt](https://github.com/AliceO2Group/AliceO2/files/1718957/log.txt)

**Comment by sawenzel** [comment]
@bovulpes: Thanks for reporting this. I will take a look. Since when do you observe this error?

**Comment by sawenzel** [comment]
@bovulpes: One try: Can you please take out the include `base/include/TPCBase/CalDet.h:14:#include <Vc/Vc>` and see if it compiles? It does not seem to be used anywhere as far as I can see.

**Comment by bovulpes** [comment]
Since yesterday afternoon.
Taking out the include you suggest fixes the problem.
Thanks a lot.
