### ISSUE TITLE
DPL input-output matching fails sporadically

### ISSUE THREAD

**Issue by matthiasrichter** [AliceO2Group/AliceO2#884]
DPL input-output matching fails sporadically if the data origin in the Input/OutputSpec has four characters, i.e. the string is not forced to be 0 terminated. Maybe the matching is done by string instead by the integral number of the `Descriptor`.

**Comment by ktf** [comment]
The matching should be done by `DataSpecUtils::match` which uses `operator==`. Is that falling back to a string comparison?
