### ISSUE TITLE
Comparison for unsigned >= 0 in devices/aliceHLTwrapper/Component.cxx

### ISSUE THREAD

**Issue by ktf** [AliceO2Group/AliceO2#90]
@matthiasrichter looks like you have a tautological comparison at line 267 of devices/aliceHLTwrapper/Component.cxx:

```
>>  if (outputBlockCnt >= 0) {
```

where `outputBlockCnt` is unsigned. Shall we just drop the check?

**Comment by matthiasrichter** [comment]
sorry for the slow response, I will fix it now and make a pull request

**Comment by ktf** [comment]
Thanks. For the record, if you say "Fix #90" it actually closes the issue as well and adds a link.
