### ISSUE TITLE
DPL opens multiple DebugGUIs

### ISSUE THREAD

**Issue by matthiasrichter** [AliceO2Group/AliceO2#916]
Since PR #860 the DPL opens a GUI window for each of the processes, where the windows of the child processes are not responsive.

The problem is probably that `runStateMachine` is invoked for the main process and all forked childs. If batch mode is not active, a new window is created with `initGUI` every time. I suppose we want to create only one instance at top level and use it everywhere.

**Comment by ktf** [comment]
yes, this is definitely a bug, but I've not seen it so far. I will try to reproduce.

**Comment by matthiasrichter** [comment]
In my case, any of the framework core unit tests opens multiple windows.

**Comment by aphecetche** [comment]
Actually, to be precise, what I get is one (useable) DebugGUI window and one (non responsive/accessible) "exec" window per device. i.e., in the attached capture, 4 windows labelled "mch-hit-generator" (name of the workflow executable) with only one useful.

<img width="1912" alt="capture" src="https://user-images.githubusercontent.com/1566009/38028131-39ae4fec-3292-11e8-9cee-b3e296014182.png">

**Comment by ktf** [comment]
This is obviously a bug. I will check but I am currently at a workshop.
