### ISSUE TITLE
Build error from o2::TPC::TPCCATracking

### ISSUE THREAD

**Issue by bovulpes** [AliceO2Group/AliceO2#938]
Since few days I can not build O2 anymore:

sw/SOURCES/O2/mft-trac/0/Detectors/TPC/reconstruction/src/TPCCATracking.cxx:201:20: error: 'struct AliHLTTPCCAClusterData::Data' has no member named 'fFlags'
         hltCluster.fFlags = cluster.getFlags();
TPCCATracking.cxx:375:27: error: 'class AliHLTTPCCAO2Interface' has no member named 'GetClusterErrors2'
   mTrackingCAO2Interface->GetClusterErrors2(row, z, sinPhi, DzDs, ErrY2, ErrZ2);
...
...
...

**Comment by davidrohr** [comment]
Hi,

could you please verify whether O2HLTCATracking is up to date!
ALIDIST recipe ...../alidist/o2hltcatracking.sh
It should be at least version hlt_o2_ca_tracking-v1.7.

Cheers
David

**Comment by bovulpes** [comment]
It's v1.6, I will update it, thanks.
