### ISSUE TITLE
[DPL] Question on (InputSpec) SubSpecification 

### ISSUE THREAD

**Issue by aphecetche** [AliceO2Group/AliceO2#944]
I have an AlgorithmSpec which takes an option that tells it which part of a given input it should handle (in this case the detection element id = detector part). 

When I build my workflow, how should I "sync" that information with the definition of the input itself ? 

For the moment I'm doing the following which is obviously wrong, as the input spec parameter `detElemId`has no relationship whatsoever with the algorithm option `--deid` value (and so I can easily launch a workflow where my algorithm is waiting for some input that will never be there ?)  

```c++
of::ConfigParamSpec detElemIdOption(const char* help, int detElemId=512)
{
  return of::ConfigParamSpec("deid", of::VariantType::Int, detElemId, { help });
}

of::DataProcessorSpec hitDumper(uint detElemId)
{
  return {
    // clang-format off
      "mch-hit-dumper",
      of::Inputs{{"mch-hits", "MCH", "HITS", detElemId, of::InputSpec::Lifetime::Timeframe}},
      noOutput,
      of::AlgorithmSpec{[](of::ProcessingContext& ctx) {
        LOG(INFO) << "hit dump";
        auto hits = ctx.inputs().get("mch-hits");
        LOG(INFO) << "Header=" << hits.header;
        hits.spec->origin.print();
      }},
      { detElemIdOption("which detection element to dump hit for") }
    // clang-format on
  };
}

of::WorkflowSpec hitGeneratorWorkflow(uint detElemId)
{
  return {
    // clang-format off
      hitGeneratorSpec(detElemId),
      hitDumper(detElemId)
      // digitizer(detElemId),
      // preclusterizerSpec(detElemId)
    // clang-format on
  };
}

void defineDataProcessing(of::WorkflowSpec& specs)
{
  of::WorkflowSpec workflow{ hitGeneratorWorkflow(512) };

  specs.swap(workflow);
}
```

Should I modify the input from e.g. the init callback to "pass it" the `--deid` option value for instance  ? Or is there some recommend way to do that ? (or not do that ;-) ) ?

Thanks,

**Comment by ktf** [comment]
Maybe I do not understand your question, but wouldn't making the `detElemId` captured by the lambda solve your problem?

```C++
of::AlgorithmSpec{[detElemId](of::ProcessingContext& ctx) {
 // ...
}
```

**Comment by aphecetche** [comment]
That's a way to insure consistency between input and algo, yes. 
But it's not controllable from the command line option. Assuming my workflow exe is called mch-hit-generator, I'm calling it like : 

```
mch-hit-generator --mch-hit-generator "--deid 512" --mch-hit-dumper "--deid 512"
```
(which btw brings another question as to whether one can have "global options" ?)

**Comment by ktf** [comment]
Ah, ok, now I get what you want to do. You should be able to get the `DataRef` (which has an instance of the `InputSpec`) with outputs().get<DataRef>("name of the parameter") from inside the `AlgorithmSpec` lambda.

**Comment by ktf** [comment]
Mmm... no... that's not what you want to do... I need to think...

**Comment by ktf** [comment]
This is finally possible using so called "Workflow Options". You can customise your command line options for the workflow by adding your own:

```
void customize(std::vector<ConfigParamSpec> &opts) {...}
```

before including `runDataProcessing.h`. The new API for `defineDataProcessing` will provide as input a `ConfigContext` and you can invoke `ConfigContext::options()` to get the command line option at workflow configuration time. See `test_ParallelProducer` for a better example example. Feel free to ask further questions.
