### ISSUE TITLE
[DPL] Feature request - timer callbacks in Data Processor

### ISSUE THREAD

**Issue by knopers8** [AliceO2Group/AliceO2#945]
A use case:

I have a Quality Control task, that collects all input data into a histogram and publishes the histogram at the end of each cycle. The cycle duration is specified by user. So I need to trigger a process callback whenever new inputs arrive and also perform some additional publishing after a timer expires.
It would useful for me to be able to declare some TimerCallback which is invoked each x seconds.

(noting down our conversation with @ktf, so it is not forgotten)

**Comment by ktf** [comment]
I think #1319 should allow you to achieve this with an input with "Lifetime::Timer". You can configure the timer by adding (explicitly, for the moment) a ConfigParamSpec with name `period-<data-origin>-<data-description>` where `<data-origin>` and `<data-description>` are the two descriptors you provide in the InputSpec. Period is in milliseconds.

**Comment by knopers8** [comment]
Thanks, I will try it out on Monday. What do I do, if I want to use '-' in origin or description?
Do you already have in mind a final way of configuring this?

**Comment by ktf** [comment]
i think it works fine, as what matters is the final option name, not its parts. to be discussed. I would configure them via `ConfigParamSpec` so that once we integrate it with Configuration they can be controlled from there (as opposed to controlled in the code).

**Comment by ktf** [comment]
https://github.com/AliceO2Group/AliceO2/pull/1354 should cover all the use cases which are not covered already by `Lifetime::Timer`.

**Comment by knopers8** [comment]
I am not sure how does that cover my case. It is not possible to access `ProcessingContext` inside these callbacks, so I see no way of publishing something in there. I could hack it by 'stealing' the `DataAllocator` reference in the main callback, but still I wouldn't be able to flush it afterwards.

**Comment by ktf** [comment]
Ah, you are sending the histogram with the usual `make()` function? Then yes, I need to expose to you the ability to create new timeframes.

**Comment by ktf** [comment]
(I thought you were using the `RawDeviceService`, in which case you can of course grab it when you create the callback.

**Comment by knopers8** [comment]
`snapshot()`, to be exact. But yes, the next processing step (checkers) was supposed to be inside DPL as well.

**Comment by ktf** [comment]
Ok, I will expose to you the ability to create new timeframes as well.

**Comment by knopers8** [comment]
Thanks!

**Comment by ktf** [comment]
Can we consider this done?

**Comment by ktf** [comment]
Since I've merged #1483 what you mention above will not happen unless we have to much pending work to do. Would you consider that enough or do you really want to be guaranteed that the last timers are processed, no matter what?

**Comment by knopers8** [comment]
This should be enough. So how do I book a timeslice for a timer now by overwriting the oldest slot?
```
timesliceIndex.associate(<my index for timer>, findOldestSlot());
```
I am guessing this would be the way, but `findOldestSlot()` is private.

**Comment by knopers8** [comment]
@ktf What do I use instead of `bookTimeslice(i)` in the example which you once helped me to make work (link below)? I have a hard time trying to understand the new behaviour and interface of `TimesliceIndex`.
https://github.com/knopers8/AliceO2/blob/e58936f9f5b23d1fc7b40d20a6fe146e335b8961/Framework/TestWorkflows/src/timersTest.cxx#L137

**Comment by ktf** [comment]
Please have a look at #1635 and in particular the lambda at:

https://github.com/AliceO2Group/AliceO2/pull/1635/files#diff-9c6dbabb0222eb60afddc909bee831f3R54

 which you can already use now with the Idle callback in order to create a standalone timer. That said, I suppose that the PR above actually provides all you need, including non data driven timers and the possibility for timers to still be triggered if the queues are full.

**Comment by ktf** [comment]
This is done since long, I guess.
