### ISSUE TITLE
[DPL] Add support for header stack navigation

### ISSUE THREAD

**Issue by matthiasrichter** [AliceO2Group/AliceO2#950]
We should add some kind of API for adding information to the header stack and extracting this information on the receiving side. The latter is probably possible already today by using
`o2::header::get<HeaderType>(processingcontext.inputs().get("inputlabel").header)`
but not nice to write and read.

**Comment by mkrzewic** [comment]
adding is possible with e.g. Stack(Stack oldstack, NewHeader more info)
