### ISSUE TITLE
ROOTSYS needs to be defined when compiling O2.

### ISSUE THREAD

**Issue by ktf** [AliceO2Group/AliceO2#98]
Building O2 seems to require ROOTSYS to be defined. This is obviously an antipattern as it makes rebuilds dependent on your environment. IMHO this should be changed to have it as a proper cmake command line option so that one can safely do "make" without risk of picking up a different version simply because CMake decides to redo some intermediate step.

**Comment by MohammadAlTurany** [comment]
This is solved in DEV branch of FairRoot ([Pull Request 409](https://github.com/FairRootGroup/FairRoot/pull/409))
