### ISSUE TITLE
O2 workflow executable quits if gui not installed and in batch mode

### ISSUE THREAD

**Issue by sawenzel** [AliceO2Group/AliceO2#987]
My workflow devices quit unexpectly before doing something useful. I tracked down the problem to the following code, which might have a wrong logic. This causes the application to exit whenever we are in batch mode (`driverInfo.batch = true`). 

```C++
  if (driverInfo.batch || guiQuitRequested || (checkIfCanExit(infos) == true)) {
          // Something requested to quit. Let's update the GUI
          // one more time and then EXIT.
          LOG(INFO) << "Quitting";
          driverInfo.states.push_back(DriverState::QUIT_REQUESTED);
          driverInfo.states.push_back(DriverState::GUI);
  }
```

Can this be please fixed urgently? (Just taking out the check on `driverInfo.batch` does the job for me but I am not sure if this is covering all the use-cases).

**Comment by ktf** [comment]
I am looking into it.
